# Copyright 2023 Pavlo Penenko
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ATTENTION! This file has been auto-generated by
# https://github.com/ppenenko/DirectXShaderCompiler/blob/metashade/issues/9/export_intrinsics/utils/metashade/export_intrinsics.py
 
def test(sh):
	with sh.function("test_EvaluateAttributeCentroid_Float", sh.Float)():
		sh.f_EvaluateAttributeCentroid = sh.g_f.EvaluateAttributeCentroid()
		sh.return_( sh.f_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float1", sh.Float1)():
		sh.f1_EvaluateAttributeCentroid = sh.g_f1.EvaluateAttributeCentroid()
		sh.return_( sh.f1_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float2", sh.Float2)():
		sh.f2_EvaluateAttributeCentroid = sh.g_f2.EvaluateAttributeCentroid()
		sh.return_( sh.f2_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float3", sh.Float3)():
		sh.f3_EvaluateAttributeCentroid = sh.g_f3.EvaluateAttributeCentroid()
		sh.return_( sh.f3_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float4", sh.Float4)():
		sh.f4_EvaluateAttributeCentroid = sh.g_f4.EvaluateAttributeCentroid()
		sh.return_( sh.f4_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float1x1", sh.Float1x1)():
		sh.f1x1_EvaluateAttributeCentroid = sh.g_f1x1.EvaluateAttributeCentroid()
		sh.return_( sh.f1x1_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float1x2", sh.Float1x2)():
		sh.f1x2_EvaluateAttributeCentroid = sh.g_f1x2.EvaluateAttributeCentroid()
		sh.return_( sh.f1x2_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float1x3", sh.Float1x3)():
		sh.f1x3_EvaluateAttributeCentroid = sh.g_f1x3.EvaluateAttributeCentroid()
		sh.return_( sh.f1x3_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float1x4", sh.Float1x4)():
		sh.f1x4_EvaluateAttributeCentroid = sh.g_f1x4.EvaluateAttributeCentroid()
		sh.return_( sh.f1x4_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float2x1", sh.Float2x1)():
		sh.f2x1_EvaluateAttributeCentroid = sh.g_f2x1.EvaluateAttributeCentroid()
		sh.return_( sh.f2x1_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float2x2", sh.Float2x2)():
		sh.f2x2_EvaluateAttributeCentroid = sh.g_f2x2.EvaluateAttributeCentroid()
		sh.return_( sh.f2x2_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float2x3", sh.Float2x3)():
		sh.f2x3_EvaluateAttributeCentroid = sh.g_f2x3.EvaluateAttributeCentroid()
		sh.return_( sh.f2x3_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float2x4", sh.Float2x4)():
		sh.f2x4_EvaluateAttributeCentroid = sh.g_f2x4.EvaluateAttributeCentroid()
		sh.return_( sh.f2x4_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float3x1", sh.Float3x1)():
		sh.f3x1_EvaluateAttributeCentroid = sh.g_f3x1.EvaluateAttributeCentroid()
		sh.return_( sh.f3x1_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float3x2", sh.Float3x2)():
		sh.f3x2_EvaluateAttributeCentroid = sh.g_f3x2.EvaluateAttributeCentroid()
		sh.return_( sh.f3x2_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float3x3", sh.Float3x3)():
		sh.f3x3_EvaluateAttributeCentroid = sh.g_f3x3.EvaluateAttributeCentroid()
		sh.return_( sh.f3x3_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float3x4", sh.Float3x4)():
		sh.f3x4_EvaluateAttributeCentroid = sh.g_f3x4.EvaluateAttributeCentroid()
		sh.return_( sh.f3x4_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float4x1", sh.Float4x1)():
		sh.f4x1_EvaluateAttributeCentroid = sh.g_f4x1.EvaluateAttributeCentroid()
		sh.return_( sh.f4x1_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float4x2", sh.Float4x2)():
		sh.f4x2_EvaluateAttributeCentroid = sh.g_f4x2.EvaluateAttributeCentroid()
		sh.return_( sh.f4x2_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float4x3", sh.Float4x3)():
		sh.f4x3_EvaluateAttributeCentroid = sh.g_f4x3.EvaluateAttributeCentroid()
		sh.return_( sh.f4x3_EvaluateAttributeCentroid )

	with sh.function("test_EvaluateAttributeCentroid_Float4x4", sh.Float4x4)():
		sh.f4x4_EvaluateAttributeCentroid = sh.g_f4x4.EvaluateAttributeCentroid()
		sh.return_( sh.f4x4_EvaluateAttributeCentroid )

	with sh.function("test_QuadReadAcrossDiagonal_Float", sh.Float)():
		sh.f_QuadReadAcrossDiagonal = sh.g_f.QuadReadAcrossDiagonal()
		sh.return_( sh.f_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float1", sh.Float1)():
		sh.f1_QuadReadAcrossDiagonal = sh.g_f1.QuadReadAcrossDiagonal()
		sh.return_( sh.f1_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float2", sh.Float2)():
		sh.f2_QuadReadAcrossDiagonal = sh.g_f2.QuadReadAcrossDiagonal()
		sh.return_( sh.f2_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float3", sh.Float3)():
		sh.f3_QuadReadAcrossDiagonal = sh.g_f3.QuadReadAcrossDiagonal()
		sh.return_( sh.f3_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float4", sh.Float4)():
		sh.f4_QuadReadAcrossDiagonal = sh.g_f4.QuadReadAcrossDiagonal()
		sh.return_( sh.f4_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float1x1", sh.Float1x1)():
		sh.f1x1_QuadReadAcrossDiagonal = sh.g_f1x1.QuadReadAcrossDiagonal()
		sh.return_( sh.f1x1_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float1x2", sh.Float1x2)():
		sh.f1x2_QuadReadAcrossDiagonal = sh.g_f1x2.QuadReadAcrossDiagonal()
		sh.return_( sh.f1x2_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float1x3", sh.Float1x3)():
		sh.f1x3_QuadReadAcrossDiagonal = sh.g_f1x3.QuadReadAcrossDiagonal()
		sh.return_( sh.f1x3_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float1x4", sh.Float1x4)():
		sh.f1x4_QuadReadAcrossDiagonal = sh.g_f1x4.QuadReadAcrossDiagonal()
		sh.return_( sh.f1x4_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float2x1", sh.Float2x1)():
		sh.f2x1_QuadReadAcrossDiagonal = sh.g_f2x1.QuadReadAcrossDiagonal()
		sh.return_( sh.f2x1_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float2x2", sh.Float2x2)():
		sh.f2x2_QuadReadAcrossDiagonal = sh.g_f2x2.QuadReadAcrossDiagonal()
		sh.return_( sh.f2x2_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float2x3", sh.Float2x3)():
		sh.f2x3_QuadReadAcrossDiagonal = sh.g_f2x3.QuadReadAcrossDiagonal()
		sh.return_( sh.f2x3_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float2x4", sh.Float2x4)():
		sh.f2x4_QuadReadAcrossDiagonal = sh.g_f2x4.QuadReadAcrossDiagonal()
		sh.return_( sh.f2x4_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float3x1", sh.Float3x1)():
		sh.f3x1_QuadReadAcrossDiagonal = sh.g_f3x1.QuadReadAcrossDiagonal()
		sh.return_( sh.f3x1_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float3x2", sh.Float3x2)():
		sh.f3x2_QuadReadAcrossDiagonal = sh.g_f3x2.QuadReadAcrossDiagonal()
		sh.return_( sh.f3x2_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float3x3", sh.Float3x3)():
		sh.f3x3_QuadReadAcrossDiagonal = sh.g_f3x3.QuadReadAcrossDiagonal()
		sh.return_( sh.f3x3_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float3x4", sh.Float3x4)():
		sh.f3x4_QuadReadAcrossDiagonal = sh.g_f3x4.QuadReadAcrossDiagonal()
		sh.return_( sh.f3x4_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float4x1", sh.Float4x1)():
		sh.f4x1_QuadReadAcrossDiagonal = sh.g_f4x1.QuadReadAcrossDiagonal()
		sh.return_( sh.f4x1_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float4x2", sh.Float4x2)():
		sh.f4x2_QuadReadAcrossDiagonal = sh.g_f4x2.QuadReadAcrossDiagonal()
		sh.return_( sh.f4x2_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float4x3", sh.Float4x3)():
		sh.f4x3_QuadReadAcrossDiagonal = sh.g_f4x3.QuadReadAcrossDiagonal()
		sh.return_( sh.f4x3_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossDiagonal_Float4x4", sh.Float4x4)():
		sh.f4x4_QuadReadAcrossDiagonal = sh.g_f4x4.QuadReadAcrossDiagonal()
		sh.return_( sh.f4x4_QuadReadAcrossDiagonal )

	with sh.function("test_QuadReadAcrossX_Float", sh.Float)():
		sh.f_QuadReadAcrossX = sh.g_f.QuadReadAcrossX()
		sh.return_( sh.f_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float1", sh.Float1)():
		sh.f1_QuadReadAcrossX = sh.g_f1.QuadReadAcrossX()
		sh.return_( sh.f1_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float2", sh.Float2)():
		sh.f2_QuadReadAcrossX = sh.g_f2.QuadReadAcrossX()
		sh.return_( sh.f2_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float3", sh.Float3)():
		sh.f3_QuadReadAcrossX = sh.g_f3.QuadReadAcrossX()
		sh.return_( sh.f3_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float4", sh.Float4)():
		sh.f4_QuadReadAcrossX = sh.g_f4.QuadReadAcrossX()
		sh.return_( sh.f4_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float1x1", sh.Float1x1)():
		sh.f1x1_QuadReadAcrossX = sh.g_f1x1.QuadReadAcrossX()
		sh.return_( sh.f1x1_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float1x2", sh.Float1x2)():
		sh.f1x2_QuadReadAcrossX = sh.g_f1x2.QuadReadAcrossX()
		sh.return_( sh.f1x2_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float1x3", sh.Float1x3)():
		sh.f1x3_QuadReadAcrossX = sh.g_f1x3.QuadReadAcrossX()
		sh.return_( sh.f1x3_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float1x4", sh.Float1x4)():
		sh.f1x4_QuadReadAcrossX = sh.g_f1x4.QuadReadAcrossX()
		sh.return_( sh.f1x4_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float2x1", sh.Float2x1)():
		sh.f2x1_QuadReadAcrossX = sh.g_f2x1.QuadReadAcrossX()
		sh.return_( sh.f2x1_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float2x2", sh.Float2x2)():
		sh.f2x2_QuadReadAcrossX = sh.g_f2x2.QuadReadAcrossX()
		sh.return_( sh.f2x2_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float2x3", sh.Float2x3)():
		sh.f2x3_QuadReadAcrossX = sh.g_f2x3.QuadReadAcrossX()
		sh.return_( sh.f2x3_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float2x4", sh.Float2x4)():
		sh.f2x4_QuadReadAcrossX = sh.g_f2x4.QuadReadAcrossX()
		sh.return_( sh.f2x4_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float3x1", sh.Float3x1)():
		sh.f3x1_QuadReadAcrossX = sh.g_f3x1.QuadReadAcrossX()
		sh.return_( sh.f3x1_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float3x2", sh.Float3x2)():
		sh.f3x2_QuadReadAcrossX = sh.g_f3x2.QuadReadAcrossX()
		sh.return_( sh.f3x2_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float3x3", sh.Float3x3)():
		sh.f3x3_QuadReadAcrossX = sh.g_f3x3.QuadReadAcrossX()
		sh.return_( sh.f3x3_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float3x4", sh.Float3x4)():
		sh.f3x4_QuadReadAcrossX = sh.g_f3x4.QuadReadAcrossX()
		sh.return_( sh.f3x4_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float4x1", sh.Float4x1)():
		sh.f4x1_QuadReadAcrossX = sh.g_f4x1.QuadReadAcrossX()
		sh.return_( sh.f4x1_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float4x2", sh.Float4x2)():
		sh.f4x2_QuadReadAcrossX = sh.g_f4x2.QuadReadAcrossX()
		sh.return_( sh.f4x2_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float4x3", sh.Float4x3)():
		sh.f4x3_QuadReadAcrossX = sh.g_f4x3.QuadReadAcrossX()
		sh.return_( sh.f4x3_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossX_Float4x4", sh.Float4x4)():
		sh.f4x4_QuadReadAcrossX = sh.g_f4x4.QuadReadAcrossX()
		sh.return_( sh.f4x4_QuadReadAcrossX )

	with sh.function("test_QuadReadAcrossY_Float", sh.Float)():
		sh.f_QuadReadAcrossY = sh.g_f.QuadReadAcrossY()
		sh.return_( sh.f_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float1", sh.Float1)():
		sh.f1_QuadReadAcrossY = sh.g_f1.QuadReadAcrossY()
		sh.return_( sh.f1_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float2", sh.Float2)():
		sh.f2_QuadReadAcrossY = sh.g_f2.QuadReadAcrossY()
		sh.return_( sh.f2_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float3", sh.Float3)():
		sh.f3_QuadReadAcrossY = sh.g_f3.QuadReadAcrossY()
		sh.return_( sh.f3_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float4", sh.Float4)():
		sh.f4_QuadReadAcrossY = sh.g_f4.QuadReadAcrossY()
		sh.return_( sh.f4_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float1x1", sh.Float1x1)():
		sh.f1x1_QuadReadAcrossY = sh.g_f1x1.QuadReadAcrossY()
		sh.return_( sh.f1x1_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float1x2", sh.Float1x2)():
		sh.f1x2_QuadReadAcrossY = sh.g_f1x2.QuadReadAcrossY()
		sh.return_( sh.f1x2_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float1x3", sh.Float1x3)():
		sh.f1x3_QuadReadAcrossY = sh.g_f1x3.QuadReadAcrossY()
		sh.return_( sh.f1x3_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float1x4", sh.Float1x4)():
		sh.f1x4_QuadReadAcrossY = sh.g_f1x4.QuadReadAcrossY()
		sh.return_( sh.f1x4_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float2x1", sh.Float2x1)():
		sh.f2x1_QuadReadAcrossY = sh.g_f2x1.QuadReadAcrossY()
		sh.return_( sh.f2x1_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float2x2", sh.Float2x2)():
		sh.f2x2_QuadReadAcrossY = sh.g_f2x2.QuadReadAcrossY()
		sh.return_( sh.f2x2_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float2x3", sh.Float2x3)():
		sh.f2x3_QuadReadAcrossY = sh.g_f2x3.QuadReadAcrossY()
		sh.return_( sh.f2x3_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float2x4", sh.Float2x4)():
		sh.f2x4_QuadReadAcrossY = sh.g_f2x4.QuadReadAcrossY()
		sh.return_( sh.f2x4_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float3x1", sh.Float3x1)():
		sh.f3x1_QuadReadAcrossY = sh.g_f3x1.QuadReadAcrossY()
		sh.return_( sh.f3x1_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float3x2", sh.Float3x2)():
		sh.f3x2_QuadReadAcrossY = sh.g_f3x2.QuadReadAcrossY()
		sh.return_( sh.f3x2_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float3x3", sh.Float3x3)():
		sh.f3x3_QuadReadAcrossY = sh.g_f3x3.QuadReadAcrossY()
		sh.return_( sh.f3x3_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float3x4", sh.Float3x4)():
		sh.f3x4_QuadReadAcrossY = sh.g_f3x4.QuadReadAcrossY()
		sh.return_( sh.f3x4_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float4x1", sh.Float4x1)():
		sh.f4x1_QuadReadAcrossY = sh.g_f4x1.QuadReadAcrossY()
		sh.return_( sh.f4x1_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float4x2", sh.Float4x2)():
		sh.f4x2_QuadReadAcrossY = sh.g_f4x2.QuadReadAcrossY()
		sh.return_( sh.f4x2_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float4x3", sh.Float4x3)():
		sh.f4x3_QuadReadAcrossY = sh.g_f4x3.QuadReadAcrossY()
		sh.return_( sh.f4x3_QuadReadAcrossY )

	with sh.function("test_QuadReadAcrossY_Float4x4", sh.Float4x4)():
		sh.f4x4_QuadReadAcrossY = sh.g_f4x4.QuadReadAcrossY()
		sh.return_( sh.f4x4_QuadReadAcrossY )

	with sh.function("test_WaveActiveMax_Float", sh.Float)():
		sh.f_WaveActiveMax = sh.g_f.WaveActiveMax()
		sh.return_( sh.f_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float1", sh.Float1)():
		sh.f1_WaveActiveMax = sh.g_f1.WaveActiveMax()
		sh.return_( sh.f1_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float2", sh.Float2)():
		sh.f2_WaveActiveMax = sh.g_f2.WaveActiveMax()
		sh.return_( sh.f2_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float3", sh.Float3)():
		sh.f3_WaveActiveMax = sh.g_f3.WaveActiveMax()
		sh.return_( sh.f3_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float4", sh.Float4)():
		sh.f4_WaveActiveMax = sh.g_f4.WaveActiveMax()
		sh.return_( sh.f4_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float1x1", sh.Float1x1)():
		sh.f1x1_WaveActiveMax = sh.g_f1x1.WaveActiveMax()
		sh.return_( sh.f1x1_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float1x2", sh.Float1x2)():
		sh.f1x2_WaveActiveMax = sh.g_f1x2.WaveActiveMax()
		sh.return_( sh.f1x2_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float1x3", sh.Float1x3)():
		sh.f1x3_WaveActiveMax = sh.g_f1x3.WaveActiveMax()
		sh.return_( sh.f1x3_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float1x4", sh.Float1x4)():
		sh.f1x4_WaveActiveMax = sh.g_f1x4.WaveActiveMax()
		sh.return_( sh.f1x4_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float2x1", sh.Float2x1)():
		sh.f2x1_WaveActiveMax = sh.g_f2x1.WaveActiveMax()
		sh.return_( sh.f2x1_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float2x2", sh.Float2x2)():
		sh.f2x2_WaveActiveMax = sh.g_f2x2.WaveActiveMax()
		sh.return_( sh.f2x2_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float2x3", sh.Float2x3)():
		sh.f2x3_WaveActiveMax = sh.g_f2x3.WaveActiveMax()
		sh.return_( sh.f2x3_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float2x4", sh.Float2x4)():
		sh.f2x4_WaveActiveMax = sh.g_f2x4.WaveActiveMax()
		sh.return_( sh.f2x4_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float3x1", sh.Float3x1)():
		sh.f3x1_WaveActiveMax = sh.g_f3x1.WaveActiveMax()
		sh.return_( sh.f3x1_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float3x2", sh.Float3x2)():
		sh.f3x2_WaveActiveMax = sh.g_f3x2.WaveActiveMax()
		sh.return_( sh.f3x2_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float3x3", sh.Float3x3)():
		sh.f3x3_WaveActiveMax = sh.g_f3x3.WaveActiveMax()
		sh.return_( sh.f3x3_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float3x4", sh.Float3x4)():
		sh.f3x4_WaveActiveMax = sh.g_f3x4.WaveActiveMax()
		sh.return_( sh.f3x4_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float4x1", sh.Float4x1)():
		sh.f4x1_WaveActiveMax = sh.g_f4x1.WaveActiveMax()
		sh.return_( sh.f4x1_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float4x2", sh.Float4x2)():
		sh.f4x2_WaveActiveMax = sh.g_f4x2.WaveActiveMax()
		sh.return_( sh.f4x2_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float4x3", sh.Float4x3)():
		sh.f4x3_WaveActiveMax = sh.g_f4x3.WaveActiveMax()
		sh.return_( sh.f4x3_WaveActiveMax )

	with sh.function("test_WaveActiveMax_Float4x4", sh.Float4x4)():
		sh.f4x4_WaveActiveMax = sh.g_f4x4.WaveActiveMax()
		sh.return_( sh.f4x4_WaveActiveMax )

	with sh.function("test_WaveActiveMin_Float", sh.Float)():
		sh.f_WaveActiveMin = sh.g_f.WaveActiveMin()
		sh.return_( sh.f_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float1", sh.Float1)():
		sh.f1_WaveActiveMin = sh.g_f1.WaveActiveMin()
		sh.return_( sh.f1_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float2", sh.Float2)():
		sh.f2_WaveActiveMin = sh.g_f2.WaveActiveMin()
		sh.return_( sh.f2_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float3", sh.Float3)():
		sh.f3_WaveActiveMin = sh.g_f3.WaveActiveMin()
		sh.return_( sh.f3_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float4", sh.Float4)():
		sh.f4_WaveActiveMin = sh.g_f4.WaveActiveMin()
		sh.return_( sh.f4_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float1x1", sh.Float1x1)():
		sh.f1x1_WaveActiveMin = sh.g_f1x1.WaveActiveMin()
		sh.return_( sh.f1x1_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float1x2", sh.Float1x2)():
		sh.f1x2_WaveActiveMin = sh.g_f1x2.WaveActiveMin()
		sh.return_( sh.f1x2_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float1x3", sh.Float1x3)():
		sh.f1x3_WaveActiveMin = sh.g_f1x3.WaveActiveMin()
		sh.return_( sh.f1x3_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float1x4", sh.Float1x4)():
		sh.f1x4_WaveActiveMin = sh.g_f1x4.WaveActiveMin()
		sh.return_( sh.f1x4_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float2x1", sh.Float2x1)():
		sh.f2x1_WaveActiveMin = sh.g_f2x1.WaveActiveMin()
		sh.return_( sh.f2x1_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float2x2", sh.Float2x2)():
		sh.f2x2_WaveActiveMin = sh.g_f2x2.WaveActiveMin()
		sh.return_( sh.f2x2_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float2x3", sh.Float2x3)():
		sh.f2x3_WaveActiveMin = sh.g_f2x3.WaveActiveMin()
		sh.return_( sh.f2x3_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float2x4", sh.Float2x4)():
		sh.f2x4_WaveActiveMin = sh.g_f2x4.WaveActiveMin()
		sh.return_( sh.f2x4_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float3x1", sh.Float3x1)():
		sh.f3x1_WaveActiveMin = sh.g_f3x1.WaveActiveMin()
		sh.return_( sh.f3x1_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float3x2", sh.Float3x2)():
		sh.f3x2_WaveActiveMin = sh.g_f3x2.WaveActiveMin()
		sh.return_( sh.f3x2_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float3x3", sh.Float3x3)():
		sh.f3x3_WaveActiveMin = sh.g_f3x3.WaveActiveMin()
		sh.return_( sh.f3x3_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float3x4", sh.Float3x4)():
		sh.f3x4_WaveActiveMin = sh.g_f3x4.WaveActiveMin()
		sh.return_( sh.f3x4_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float4x1", sh.Float4x1)():
		sh.f4x1_WaveActiveMin = sh.g_f4x1.WaveActiveMin()
		sh.return_( sh.f4x1_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float4x2", sh.Float4x2)():
		sh.f4x2_WaveActiveMin = sh.g_f4x2.WaveActiveMin()
		sh.return_( sh.f4x2_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float4x3", sh.Float4x3)():
		sh.f4x3_WaveActiveMin = sh.g_f4x3.WaveActiveMin()
		sh.return_( sh.f4x3_WaveActiveMin )

	with sh.function("test_WaveActiveMin_Float4x4", sh.Float4x4)():
		sh.f4x4_WaveActiveMin = sh.g_f4x4.WaveActiveMin()
		sh.return_( sh.f4x4_WaveActiveMin )

	with sh.function("test_WaveActiveProduct_Float", sh.Float)():
		sh.f_WaveActiveProduct = sh.g_f.WaveActiveProduct()
		sh.return_( sh.f_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float1", sh.Float1)():
		sh.f1_WaveActiveProduct = sh.g_f1.WaveActiveProduct()
		sh.return_( sh.f1_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float2", sh.Float2)():
		sh.f2_WaveActiveProduct = sh.g_f2.WaveActiveProduct()
		sh.return_( sh.f2_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float3", sh.Float3)():
		sh.f3_WaveActiveProduct = sh.g_f3.WaveActiveProduct()
		sh.return_( sh.f3_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float4", sh.Float4)():
		sh.f4_WaveActiveProduct = sh.g_f4.WaveActiveProduct()
		sh.return_( sh.f4_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float1x1", sh.Float1x1)():
		sh.f1x1_WaveActiveProduct = sh.g_f1x1.WaveActiveProduct()
		sh.return_( sh.f1x1_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float1x2", sh.Float1x2)():
		sh.f1x2_WaveActiveProduct = sh.g_f1x2.WaveActiveProduct()
		sh.return_( sh.f1x2_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float1x3", sh.Float1x3)():
		sh.f1x3_WaveActiveProduct = sh.g_f1x3.WaveActiveProduct()
		sh.return_( sh.f1x3_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float1x4", sh.Float1x4)():
		sh.f1x4_WaveActiveProduct = sh.g_f1x4.WaveActiveProduct()
		sh.return_( sh.f1x4_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float2x1", sh.Float2x1)():
		sh.f2x1_WaveActiveProduct = sh.g_f2x1.WaveActiveProduct()
		sh.return_( sh.f2x1_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float2x2", sh.Float2x2)():
		sh.f2x2_WaveActiveProduct = sh.g_f2x2.WaveActiveProduct()
		sh.return_( sh.f2x2_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float2x3", sh.Float2x3)():
		sh.f2x3_WaveActiveProduct = sh.g_f2x3.WaveActiveProduct()
		sh.return_( sh.f2x3_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float2x4", sh.Float2x4)():
		sh.f2x4_WaveActiveProduct = sh.g_f2x4.WaveActiveProduct()
		sh.return_( sh.f2x4_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float3x1", sh.Float3x1)():
		sh.f3x1_WaveActiveProduct = sh.g_f3x1.WaveActiveProduct()
		sh.return_( sh.f3x1_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float3x2", sh.Float3x2)():
		sh.f3x2_WaveActiveProduct = sh.g_f3x2.WaveActiveProduct()
		sh.return_( sh.f3x2_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float3x3", sh.Float3x3)():
		sh.f3x3_WaveActiveProduct = sh.g_f3x3.WaveActiveProduct()
		sh.return_( sh.f3x3_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float3x4", sh.Float3x4)():
		sh.f3x4_WaveActiveProduct = sh.g_f3x4.WaveActiveProduct()
		sh.return_( sh.f3x4_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float4x1", sh.Float4x1)():
		sh.f4x1_WaveActiveProduct = sh.g_f4x1.WaveActiveProduct()
		sh.return_( sh.f4x1_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float4x2", sh.Float4x2)():
		sh.f4x2_WaveActiveProduct = sh.g_f4x2.WaveActiveProduct()
		sh.return_( sh.f4x2_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float4x3", sh.Float4x3)():
		sh.f4x3_WaveActiveProduct = sh.g_f4x3.WaveActiveProduct()
		sh.return_( sh.f4x3_WaveActiveProduct )

	with sh.function("test_WaveActiveProduct_Float4x4", sh.Float4x4)():
		sh.f4x4_WaveActiveProduct = sh.g_f4x4.WaveActiveProduct()
		sh.return_( sh.f4x4_WaveActiveProduct )

	with sh.function("test_WaveActiveSum_Float", sh.Float)():
		sh.f_WaveActiveSum = sh.g_f.WaveActiveSum()
		sh.return_( sh.f_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float1", sh.Float1)():
		sh.f1_WaveActiveSum = sh.g_f1.WaveActiveSum()
		sh.return_( sh.f1_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float2", sh.Float2)():
		sh.f2_WaveActiveSum = sh.g_f2.WaveActiveSum()
		sh.return_( sh.f2_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float3", sh.Float3)():
		sh.f3_WaveActiveSum = sh.g_f3.WaveActiveSum()
		sh.return_( sh.f3_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float4", sh.Float4)():
		sh.f4_WaveActiveSum = sh.g_f4.WaveActiveSum()
		sh.return_( sh.f4_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float1x1", sh.Float1x1)():
		sh.f1x1_WaveActiveSum = sh.g_f1x1.WaveActiveSum()
		sh.return_( sh.f1x1_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float1x2", sh.Float1x2)():
		sh.f1x2_WaveActiveSum = sh.g_f1x2.WaveActiveSum()
		sh.return_( sh.f1x2_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float1x3", sh.Float1x3)():
		sh.f1x3_WaveActiveSum = sh.g_f1x3.WaveActiveSum()
		sh.return_( sh.f1x3_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float1x4", sh.Float1x4)():
		sh.f1x4_WaveActiveSum = sh.g_f1x4.WaveActiveSum()
		sh.return_( sh.f1x4_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float2x1", sh.Float2x1)():
		sh.f2x1_WaveActiveSum = sh.g_f2x1.WaveActiveSum()
		sh.return_( sh.f2x1_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float2x2", sh.Float2x2)():
		sh.f2x2_WaveActiveSum = sh.g_f2x2.WaveActiveSum()
		sh.return_( sh.f2x2_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float2x3", sh.Float2x3)():
		sh.f2x3_WaveActiveSum = sh.g_f2x3.WaveActiveSum()
		sh.return_( sh.f2x3_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float2x4", sh.Float2x4)():
		sh.f2x4_WaveActiveSum = sh.g_f2x4.WaveActiveSum()
		sh.return_( sh.f2x4_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float3x1", sh.Float3x1)():
		sh.f3x1_WaveActiveSum = sh.g_f3x1.WaveActiveSum()
		sh.return_( sh.f3x1_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float3x2", sh.Float3x2)():
		sh.f3x2_WaveActiveSum = sh.g_f3x2.WaveActiveSum()
		sh.return_( sh.f3x2_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float3x3", sh.Float3x3)():
		sh.f3x3_WaveActiveSum = sh.g_f3x3.WaveActiveSum()
		sh.return_( sh.f3x3_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float3x4", sh.Float3x4)():
		sh.f3x4_WaveActiveSum = sh.g_f3x4.WaveActiveSum()
		sh.return_( sh.f3x4_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float4x1", sh.Float4x1)():
		sh.f4x1_WaveActiveSum = sh.g_f4x1.WaveActiveSum()
		sh.return_( sh.f4x1_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float4x2", sh.Float4x2)():
		sh.f4x2_WaveActiveSum = sh.g_f4x2.WaveActiveSum()
		sh.return_( sh.f4x2_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float4x3", sh.Float4x3)():
		sh.f4x3_WaveActiveSum = sh.g_f4x3.WaveActiveSum()
		sh.return_( sh.f4x3_WaveActiveSum )

	with sh.function("test_WaveActiveSum_Float4x4", sh.Float4x4)():
		sh.f4x4_WaveActiveSum = sh.g_f4x4.WaveActiveSum()
		sh.return_( sh.f4x4_WaveActiveSum )

	with sh.function("test_WavePrefixProduct_Float", sh.Float)():
		sh.f_WavePrefixProduct = sh.g_f.WavePrefixProduct()
		sh.return_( sh.f_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float1", sh.Float1)():
		sh.f1_WavePrefixProduct = sh.g_f1.WavePrefixProduct()
		sh.return_( sh.f1_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float2", sh.Float2)():
		sh.f2_WavePrefixProduct = sh.g_f2.WavePrefixProduct()
		sh.return_( sh.f2_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float3", sh.Float3)():
		sh.f3_WavePrefixProduct = sh.g_f3.WavePrefixProduct()
		sh.return_( sh.f3_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float4", sh.Float4)():
		sh.f4_WavePrefixProduct = sh.g_f4.WavePrefixProduct()
		sh.return_( sh.f4_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float1x1", sh.Float1x1)():
		sh.f1x1_WavePrefixProduct = sh.g_f1x1.WavePrefixProduct()
		sh.return_( sh.f1x1_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float1x2", sh.Float1x2)():
		sh.f1x2_WavePrefixProduct = sh.g_f1x2.WavePrefixProduct()
		sh.return_( sh.f1x2_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float1x3", sh.Float1x3)():
		sh.f1x3_WavePrefixProduct = sh.g_f1x3.WavePrefixProduct()
		sh.return_( sh.f1x3_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float1x4", sh.Float1x4)():
		sh.f1x4_WavePrefixProduct = sh.g_f1x4.WavePrefixProduct()
		sh.return_( sh.f1x4_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float2x1", sh.Float2x1)():
		sh.f2x1_WavePrefixProduct = sh.g_f2x1.WavePrefixProduct()
		sh.return_( sh.f2x1_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float2x2", sh.Float2x2)():
		sh.f2x2_WavePrefixProduct = sh.g_f2x2.WavePrefixProduct()
		sh.return_( sh.f2x2_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float2x3", sh.Float2x3)():
		sh.f2x3_WavePrefixProduct = sh.g_f2x3.WavePrefixProduct()
		sh.return_( sh.f2x3_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float2x4", sh.Float2x4)():
		sh.f2x4_WavePrefixProduct = sh.g_f2x4.WavePrefixProduct()
		sh.return_( sh.f2x4_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float3x1", sh.Float3x1)():
		sh.f3x1_WavePrefixProduct = sh.g_f3x1.WavePrefixProduct()
		sh.return_( sh.f3x1_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float3x2", sh.Float3x2)():
		sh.f3x2_WavePrefixProduct = sh.g_f3x2.WavePrefixProduct()
		sh.return_( sh.f3x2_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float3x3", sh.Float3x3)():
		sh.f3x3_WavePrefixProduct = sh.g_f3x3.WavePrefixProduct()
		sh.return_( sh.f3x3_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float3x4", sh.Float3x4)():
		sh.f3x4_WavePrefixProduct = sh.g_f3x4.WavePrefixProduct()
		sh.return_( sh.f3x4_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float4x1", sh.Float4x1)():
		sh.f4x1_WavePrefixProduct = sh.g_f4x1.WavePrefixProduct()
		sh.return_( sh.f4x1_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float4x2", sh.Float4x2)():
		sh.f4x2_WavePrefixProduct = sh.g_f4x2.WavePrefixProduct()
		sh.return_( sh.f4x2_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float4x3", sh.Float4x3)():
		sh.f4x3_WavePrefixProduct = sh.g_f4x3.WavePrefixProduct()
		sh.return_( sh.f4x3_WavePrefixProduct )

	with sh.function("test_WavePrefixProduct_Float4x4", sh.Float4x4)():
		sh.f4x4_WavePrefixProduct = sh.g_f4x4.WavePrefixProduct()
		sh.return_( sh.f4x4_WavePrefixProduct )

	with sh.function("test_WavePrefixSum_Float", sh.Float)():
		sh.f_WavePrefixSum = sh.g_f.WavePrefixSum()
		sh.return_( sh.f_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float1", sh.Float1)():
		sh.f1_WavePrefixSum = sh.g_f1.WavePrefixSum()
		sh.return_( sh.f1_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float2", sh.Float2)():
		sh.f2_WavePrefixSum = sh.g_f2.WavePrefixSum()
		sh.return_( sh.f2_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float3", sh.Float3)():
		sh.f3_WavePrefixSum = sh.g_f3.WavePrefixSum()
		sh.return_( sh.f3_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float4", sh.Float4)():
		sh.f4_WavePrefixSum = sh.g_f4.WavePrefixSum()
		sh.return_( sh.f4_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float1x1", sh.Float1x1)():
		sh.f1x1_WavePrefixSum = sh.g_f1x1.WavePrefixSum()
		sh.return_( sh.f1x1_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float1x2", sh.Float1x2)():
		sh.f1x2_WavePrefixSum = sh.g_f1x2.WavePrefixSum()
		sh.return_( sh.f1x2_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float1x3", sh.Float1x3)():
		sh.f1x3_WavePrefixSum = sh.g_f1x3.WavePrefixSum()
		sh.return_( sh.f1x3_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float1x4", sh.Float1x4)():
		sh.f1x4_WavePrefixSum = sh.g_f1x4.WavePrefixSum()
		sh.return_( sh.f1x4_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float2x1", sh.Float2x1)():
		sh.f2x1_WavePrefixSum = sh.g_f2x1.WavePrefixSum()
		sh.return_( sh.f2x1_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float2x2", sh.Float2x2)():
		sh.f2x2_WavePrefixSum = sh.g_f2x2.WavePrefixSum()
		sh.return_( sh.f2x2_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float2x3", sh.Float2x3)():
		sh.f2x3_WavePrefixSum = sh.g_f2x3.WavePrefixSum()
		sh.return_( sh.f2x3_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float2x4", sh.Float2x4)():
		sh.f2x4_WavePrefixSum = sh.g_f2x4.WavePrefixSum()
		sh.return_( sh.f2x4_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float3x1", sh.Float3x1)():
		sh.f3x1_WavePrefixSum = sh.g_f3x1.WavePrefixSum()
		sh.return_( sh.f3x1_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float3x2", sh.Float3x2)():
		sh.f3x2_WavePrefixSum = sh.g_f3x2.WavePrefixSum()
		sh.return_( sh.f3x2_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float3x3", sh.Float3x3)():
		sh.f3x3_WavePrefixSum = sh.g_f3x3.WavePrefixSum()
		sh.return_( sh.f3x3_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float3x4", sh.Float3x4)():
		sh.f3x4_WavePrefixSum = sh.g_f3x4.WavePrefixSum()
		sh.return_( sh.f3x4_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float4x1", sh.Float4x1)():
		sh.f4x1_WavePrefixSum = sh.g_f4x1.WavePrefixSum()
		sh.return_( sh.f4x1_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float4x2", sh.Float4x2)():
		sh.f4x2_WavePrefixSum = sh.g_f4x2.WavePrefixSum()
		sh.return_( sh.f4x2_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float4x3", sh.Float4x3)():
		sh.f4x3_WavePrefixSum = sh.g_f4x3.WavePrefixSum()
		sh.return_( sh.f4x3_WavePrefixSum )

	with sh.function("test_WavePrefixSum_Float4x4", sh.Float4x4)():
		sh.f4x4_WavePrefixSum = sh.g_f4x4.WavePrefixSum()
		sh.return_( sh.f4x4_WavePrefixSum )

	with sh.function("test_abs_Float", sh.Float)():
		sh.f_abs = sh.g_f.abs()
		sh.return_( sh.f_abs )

	with sh.function("test_abs_Float1", sh.Float1)():
		sh.f1_abs = sh.g_f1.abs()
		sh.return_( sh.f1_abs )

	with sh.function("test_abs_Float2", sh.Float2)():
		sh.f2_abs = sh.g_f2.abs()
		sh.return_( sh.f2_abs )

	with sh.function("test_abs_Float3", sh.Float3)():
		sh.f3_abs = sh.g_f3.abs()
		sh.return_( sh.f3_abs )

	with sh.function("test_abs_Float4", sh.Float4)():
		sh.f4_abs = sh.g_f4.abs()
		sh.return_( sh.f4_abs )

	with sh.function("test_abs_Float1x1", sh.Float1x1)():
		sh.f1x1_abs = sh.g_f1x1.abs()
		sh.return_( sh.f1x1_abs )

	with sh.function("test_abs_Float1x2", sh.Float1x2)():
		sh.f1x2_abs = sh.g_f1x2.abs()
		sh.return_( sh.f1x2_abs )

	with sh.function("test_abs_Float1x3", sh.Float1x3)():
		sh.f1x3_abs = sh.g_f1x3.abs()
		sh.return_( sh.f1x3_abs )

	with sh.function("test_abs_Float1x4", sh.Float1x4)():
		sh.f1x4_abs = sh.g_f1x4.abs()
		sh.return_( sh.f1x4_abs )

	with sh.function("test_abs_Float2x1", sh.Float2x1)():
		sh.f2x1_abs = sh.g_f2x1.abs()
		sh.return_( sh.f2x1_abs )

	with sh.function("test_abs_Float2x2", sh.Float2x2)():
		sh.f2x2_abs = sh.g_f2x2.abs()
		sh.return_( sh.f2x2_abs )

	with sh.function("test_abs_Float2x3", sh.Float2x3)():
		sh.f2x3_abs = sh.g_f2x3.abs()
		sh.return_( sh.f2x3_abs )

	with sh.function("test_abs_Float2x4", sh.Float2x4)():
		sh.f2x4_abs = sh.g_f2x4.abs()
		sh.return_( sh.f2x4_abs )

	with sh.function("test_abs_Float3x1", sh.Float3x1)():
		sh.f3x1_abs = sh.g_f3x1.abs()
		sh.return_( sh.f3x1_abs )

	with sh.function("test_abs_Float3x2", sh.Float3x2)():
		sh.f3x2_abs = sh.g_f3x2.abs()
		sh.return_( sh.f3x2_abs )

	with sh.function("test_abs_Float3x3", sh.Float3x3)():
		sh.f3x3_abs = sh.g_f3x3.abs()
		sh.return_( sh.f3x3_abs )

	with sh.function("test_abs_Float3x4", sh.Float3x4)():
		sh.f3x4_abs = sh.g_f3x4.abs()
		sh.return_( sh.f3x4_abs )

	with sh.function("test_abs_Float4x1", sh.Float4x1)():
		sh.f4x1_abs = sh.g_f4x1.abs()
		sh.return_( sh.f4x1_abs )

	with sh.function("test_abs_Float4x2", sh.Float4x2)():
		sh.f4x2_abs = sh.g_f4x2.abs()
		sh.return_( sh.f4x2_abs )

	with sh.function("test_abs_Float4x3", sh.Float4x3)():
		sh.f4x3_abs = sh.g_f4x3.abs()
		sh.return_( sh.f4x3_abs )

	with sh.function("test_abs_Float4x4", sh.Float4x4)():
		sh.f4x4_abs = sh.g_f4x4.abs()
		sh.return_( sh.f4x4_abs )

