# Copyright 2023 Pavlo Penenko
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ATTENTION! This file has been auto-generated by
# https://github.com/metashade/DirectXShaderCompiler/blob/metashade/issues/9/export_intrinsics/utils/metashade/export_intrinsics.py
 
def test(sh):
	with sh.function("test_acos_Float", sh.Float)():
		sh.return_( sh.g_f.acos() )

	with sh.function("test_acos_Float1", sh.Float1)():
		sh.return_( sh.g_f1.acos() )

	with sh.function("test_acos_Float2", sh.Float2)():
		sh.return_( sh.g_f2.acos() )

	with sh.function("test_acos_Float3", sh.Float3)():
		sh.return_( sh.g_f3.acos() )

	with sh.function("test_acos_Float4", sh.Float4)():
		sh.return_( sh.g_f4.acos() )

	with sh.function("test_acos_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.acos() )

	with sh.function("test_acos_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.acos() )

	with sh.function("test_acos_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.acos() )

	with sh.function("test_acos_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.acos() )

	with sh.function("test_acos_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.acos() )

	with sh.function("test_acos_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.acos() )

	with sh.function("test_acos_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.acos() )

	with sh.function("test_acos_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.acos() )

	with sh.function("test_acos_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.acos() )

	with sh.function("test_acos_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.acos() )

	with sh.function("test_acos_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.acos() )

	with sh.function("test_acos_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.acos() )

	with sh.function("test_acos_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.acos() )

	with sh.function("test_acos_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.acos() )

	with sh.function("test_acos_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.acos() )

	with sh.function("test_acos_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.acos() )

	with sh.function("test_asin_Float", sh.Float)():
		sh.return_( sh.g_f.asin() )

	with sh.function("test_asin_Float1", sh.Float1)():
		sh.return_( sh.g_f1.asin() )

	with sh.function("test_asin_Float2", sh.Float2)():
		sh.return_( sh.g_f2.asin() )

	with sh.function("test_asin_Float3", sh.Float3)():
		sh.return_( sh.g_f3.asin() )

	with sh.function("test_asin_Float4", sh.Float4)():
		sh.return_( sh.g_f4.asin() )

	with sh.function("test_asin_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.asin() )

	with sh.function("test_asin_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.asin() )

	with sh.function("test_asin_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.asin() )

	with sh.function("test_asin_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.asin() )

	with sh.function("test_asin_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.asin() )

	with sh.function("test_asin_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.asin() )

	with sh.function("test_asin_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.asin() )

	with sh.function("test_asin_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.asin() )

	with sh.function("test_asin_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.asin() )

	with sh.function("test_asin_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.asin() )

	with sh.function("test_asin_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.asin() )

	with sh.function("test_asin_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.asin() )

	with sh.function("test_asin_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.asin() )

	with sh.function("test_asin_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.asin() )

	with sh.function("test_asin_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.asin() )

	with sh.function("test_asin_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.asin() )

	with sh.function("test_atan_Float", sh.Float)():
		sh.return_( sh.g_f.atan() )

	with sh.function("test_atan_Float1", sh.Float1)():
		sh.return_( sh.g_f1.atan() )

	with sh.function("test_atan_Float2", sh.Float2)():
		sh.return_( sh.g_f2.atan() )

	with sh.function("test_atan_Float3", sh.Float3)():
		sh.return_( sh.g_f3.atan() )

	with sh.function("test_atan_Float4", sh.Float4)():
		sh.return_( sh.g_f4.atan() )

	with sh.function("test_atan_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.atan() )

	with sh.function("test_atan_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.atan() )

	with sh.function("test_atan_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.atan() )

	with sh.function("test_atan_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.atan() )

	with sh.function("test_atan_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.atan() )

	with sh.function("test_atan_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.atan() )

	with sh.function("test_atan_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.atan() )

	with sh.function("test_atan_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.atan() )

	with sh.function("test_atan_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.atan() )

	with sh.function("test_atan_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.atan() )

	with sh.function("test_atan_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.atan() )

	with sh.function("test_atan_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.atan() )

	with sh.function("test_atan_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.atan() )

	with sh.function("test_atan_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.atan() )

	with sh.function("test_atan_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.atan() )

	with sh.function("test_atan_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.atan() )

	with sh.function("test_atan2_Float", sh.Float)(y = sh.Float):
		sh.return_( sh.g_f.atan2(y = sh.y) )

	with sh.function("test_atan2_Float1", sh.Float1)(y = sh.Float1):
		sh.return_( sh.g_f1.atan2(y = sh.y) )

	with sh.function("test_atan2_Float2", sh.Float2)(y = sh.Float2):
		sh.return_( sh.g_f2.atan2(y = sh.y) )

	with sh.function("test_atan2_Float3", sh.Float3)(y = sh.Float3):
		sh.return_( sh.g_f3.atan2(y = sh.y) )

	with sh.function("test_atan2_Float4", sh.Float4)(y = sh.Float4):
		sh.return_( sh.g_f4.atan2(y = sh.y) )

	with sh.function("test_atan2_Float1x1", sh.Float1x1)(y = sh.Float1x1):
		sh.return_( sh.g_f1x1.atan2(y = sh.y) )

	with sh.function("test_atan2_Float1x2", sh.Float1x2)(y = sh.Float1x2):
		sh.return_( sh.g_f1x2.atan2(y = sh.y) )

	with sh.function("test_atan2_Float1x3", sh.Float1x3)(y = sh.Float1x3):
		sh.return_( sh.g_f1x3.atan2(y = sh.y) )

	with sh.function("test_atan2_Float1x4", sh.Float1x4)(y = sh.Float1x4):
		sh.return_( sh.g_f1x4.atan2(y = sh.y) )

	with sh.function("test_atan2_Float2x1", sh.Float2x1)(y = sh.Float2x1):
		sh.return_( sh.g_f2x1.atan2(y = sh.y) )

	with sh.function("test_atan2_Float2x2", sh.Float2x2)(y = sh.Float2x2):
		sh.return_( sh.g_f2x2.atan2(y = sh.y) )

	with sh.function("test_atan2_Float2x3", sh.Float2x3)(y = sh.Float2x3):
		sh.return_( sh.g_f2x3.atan2(y = sh.y) )

	with sh.function("test_atan2_Float2x4", sh.Float2x4)(y = sh.Float2x4):
		sh.return_( sh.g_f2x4.atan2(y = sh.y) )

	with sh.function("test_atan2_Float3x1", sh.Float3x1)(y = sh.Float3x1):
		sh.return_( sh.g_f3x1.atan2(y = sh.y) )

	with sh.function("test_atan2_Float3x2", sh.Float3x2)(y = sh.Float3x2):
		sh.return_( sh.g_f3x2.atan2(y = sh.y) )

	with sh.function("test_atan2_Float3x3", sh.Float3x3)(y = sh.Float3x3):
		sh.return_( sh.g_f3x3.atan2(y = sh.y) )

	with sh.function("test_atan2_Float3x4", sh.Float3x4)(y = sh.Float3x4):
		sh.return_( sh.g_f3x4.atan2(y = sh.y) )

	with sh.function("test_atan2_Float4x1", sh.Float4x1)(y = sh.Float4x1):
		sh.return_( sh.g_f4x1.atan2(y = sh.y) )

	with sh.function("test_atan2_Float4x2", sh.Float4x2)(y = sh.Float4x2):
		sh.return_( sh.g_f4x2.atan2(y = sh.y) )

	with sh.function("test_atan2_Float4x3", sh.Float4x3)(y = sh.Float4x3):
		sh.return_( sh.g_f4x3.atan2(y = sh.y) )

	with sh.function("test_atan2_Float4x4", sh.Float4x4)(y = sh.Float4x4):
		sh.return_( sh.g_f4x4.atan2(y = sh.y) )

	with sh.function("test_ceil_Float", sh.Float)():
		sh.return_( sh.g_f.ceil() )

	with sh.function("test_ceil_Float1", sh.Float1)():
		sh.return_( sh.g_f1.ceil() )

	with sh.function("test_ceil_Float2", sh.Float2)():
		sh.return_( sh.g_f2.ceil() )

	with sh.function("test_ceil_Float3", sh.Float3)():
		sh.return_( sh.g_f3.ceil() )

	with sh.function("test_ceil_Float4", sh.Float4)():
		sh.return_( sh.g_f4.ceil() )

	with sh.function("test_ceil_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.ceil() )

	with sh.function("test_ceil_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.ceil() )

	with sh.function("test_ceil_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.ceil() )

	with sh.function("test_ceil_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.ceil() )

	with sh.function("test_ceil_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.ceil() )

	with sh.function("test_ceil_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.ceil() )

	with sh.function("test_ceil_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.ceil() )

	with sh.function("test_ceil_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.ceil() )

	with sh.function("test_ceil_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.ceil() )

	with sh.function("test_ceil_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.ceil() )

	with sh.function("test_ceil_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.ceil() )

	with sh.function("test_ceil_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.ceil() )

	with sh.function("test_ceil_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.ceil() )

	with sh.function("test_ceil_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.ceil() )

	with sh.function("test_ceil_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.ceil() )

	with sh.function("test_ceil_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.ceil() )

	with sh.function("test_clip_Float", None)():
		sh.g_f.clip()

	with sh.function("test_clip_Float1", None)():
		sh.g_f1.clip()

	with sh.function("test_clip_Float2", None)():
		sh.g_f2.clip()

	with sh.function("test_clip_Float3", None)():
		sh.g_f3.clip()

	with sh.function("test_clip_Float4", None)():
		sh.g_f4.clip()

	with sh.function("test_clip_Float1x1", None)():
		sh.g_f1x1.clip()

	with sh.function("test_clip_Float1x2", None)():
		sh.g_f1x2.clip()

	with sh.function("test_clip_Float1x3", None)():
		sh.g_f1x3.clip()

	with sh.function("test_clip_Float1x4", None)():
		sh.g_f1x4.clip()

	with sh.function("test_clip_Float2x1", None)():
		sh.g_f2x1.clip()

	with sh.function("test_clip_Float2x2", None)():
		sh.g_f2x2.clip()

	with sh.function("test_clip_Float2x3", None)():
		sh.g_f2x3.clip()

	with sh.function("test_clip_Float2x4", None)():
		sh.g_f2x4.clip()

	with sh.function("test_clip_Float3x1", None)():
		sh.g_f3x1.clip()

	with sh.function("test_clip_Float3x2", None)():
		sh.g_f3x2.clip()

	with sh.function("test_clip_Float3x3", None)():
		sh.g_f3x3.clip()

	with sh.function("test_clip_Float3x4", None)():
		sh.g_f3x4.clip()

	with sh.function("test_clip_Float4x1", None)():
		sh.g_f4x1.clip()

	with sh.function("test_clip_Float4x2", None)():
		sh.g_f4x2.clip()

	with sh.function("test_clip_Float4x3", None)():
		sh.g_f4x3.clip()

	with sh.function("test_clip_Float4x4", None)():
		sh.g_f4x4.clip()

	with sh.function("test_cos_Float", sh.Float)():
		sh.return_( sh.g_f.cos() )

	with sh.function("test_cos_Float1", sh.Float1)():
		sh.return_( sh.g_f1.cos() )

	with sh.function("test_cos_Float2", sh.Float2)():
		sh.return_( sh.g_f2.cos() )

	with sh.function("test_cos_Float3", sh.Float3)():
		sh.return_( sh.g_f3.cos() )

	with sh.function("test_cos_Float4", sh.Float4)():
		sh.return_( sh.g_f4.cos() )

	with sh.function("test_cos_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.cos() )

	with sh.function("test_cos_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.cos() )

	with sh.function("test_cos_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.cos() )

	with sh.function("test_cos_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.cos() )

	with sh.function("test_cos_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.cos() )

	with sh.function("test_cos_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.cos() )

	with sh.function("test_cos_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.cos() )

	with sh.function("test_cos_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.cos() )

	with sh.function("test_cos_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.cos() )

	with sh.function("test_cos_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.cos() )

	with sh.function("test_cos_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.cos() )

	with sh.function("test_cos_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.cos() )

	with sh.function("test_cos_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.cos() )

	with sh.function("test_cos_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.cos() )

	with sh.function("test_cos_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.cos() )

	with sh.function("test_cos_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.cos() )

	with sh.function("test_cosh_Float", sh.Float)():
		sh.return_( sh.g_f.cosh() )

	with sh.function("test_cosh_Float1", sh.Float1)():
		sh.return_( sh.g_f1.cosh() )

	with sh.function("test_cosh_Float2", sh.Float2)():
		sh.return_( sh.g_f2.cosh() )

	with sh.function("test_cosh_Float3", sh.Float3)():
		sh.return_( sh.g_f3.cosh() )

	with sh.function("test_cosh_Float4", sh.Float4)():
		sh.return_( sh.g_f4.cosh() )

	with sh.function("test_cosh_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.cosh() )

	with sh.function("test_cosh_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.cosh() )

	with sh.function("test_cosh_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.cosh() )

	with sh.function("test_cosh_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.cosh() )

	with sh.function("test_cosh_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.cosh() )

	with sh.function("test_cosh_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.cosh() )

	with sh.function("test_cosh_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.cosh() )

	with sh.function("test_cosh_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.cosh() )

	with sh.function("test_cosh_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.cosh() )

	with sh.function("test_cosh_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.cosh() )

	with sh.function("test_cosh_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.cosh() )

	with sh.function("test_cosh_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.cosh() )

	with sh.function("test_cosh_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.cosh() )

	with sh.function("test_cosh_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.cosh() )

	with sh.function("test_cosh_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.cosh() )

	with sh.function("test_cosh_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.cosh() )

	with sh.function("test_ddx_Float", sh.Float)():
		sh.return_( sh.g_f.ddx() )

	with sh.function("test_ddx_Float1", sh.Float1)():
		sh.return_( sh.g_f1.ddx() )

	with sh.function("test_ddx_Float2", sh.Float2)():
		sh.return_( sh.g_f2.ddx() )

	with sh.function("test_ddx_Float3", sh.Float3)():
		sh.return_( sh.g_f3.ddx() )

	with sh.function("test_ddx_Float4", sh.Float4)():
		sh.return_( sh.g_f4.ddx() )

	with sh.function("test_ddx_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.ddx() )

	with sh.function("test_ddx_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.ddx() )

	with sh.function("test_ddx_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.ddx() )

	with sh.function("test_ddx_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.ddx() )

	with sh.function("test_ddx_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.ddx() )

	with sh.function("test_ddx_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.ddx() )

	with sh.function("test_ddx_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.ddx() )

	with sh.function("test_ddx_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.ddx() )

	with sh.function("test_ddx_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.ddx() )

	with sh.function("test_ddx_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.ddx() )

	with sh.function("test_ddx_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.ddx() )

	with sh.function("test_ddx_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.ddx() )

	with sh.function("test_ddx_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.ddx() )

	with sh.function("test_ddx_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.ddx() )

	with sh.function("test_ddx_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.ddx() )

	with sh.function("test_ddx_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.ddx() )

	with sh.function("test_ddx_coarse_Float", sh.Float)():
		sh.return_( sh.g_f.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float1", sh.Float1)():
		sh.return_( sh.g_f1.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float2", sh.Float2)():
		sh.return_( sh.g_f2.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float3", sh.Float3)():
		sh.return_( sh.g_f3.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float4", sh.Float4)():
		sh.return_( sh.g_f4.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.ddx_coarse() )

	with sh.function("test_ddx_coarse_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.ddx_coarse() )

	with sh.function("test_ddx_fine_Float", sh.Float)():
		sh.return_( sh.g_f.ddx_fine() )

	with sh.function("test_ddx_fine_Float1", sh.Float1)():
		sh.return_( sh.g_f1.ddx_fine() )

	with sh.function("test_ddx_fine_Float2", sh.Float2)():
		sh.return_( sh.g_f2.ddx_fine() )

	with sh.function("test_ddx_fine_Float3", sh.Float3)():
		sh.return_( sh.g_f3.ddx_fine() )

	with sh.function("test_ddx_fine_Float4", sh.Float4)():
		sh.return_( sh.g_f4.ddx_fine() )

	with sh.function("test_ddx_fine_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.ddx_fine() )

	with sh.function("test_ddx_fine_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.ddx_fine() )

	with sh.function("test_ddx_fine_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.ddx_fine() )

	with sh.function("test_ddx_fine_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.ddx_fine() )

	with sh.function("test_ddx_fine_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.ddx_fine() )

	with sh.function("test_ddx_fine_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.ddx_fine() )

	with sh.function("test_ddx_fine_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.ddx_fine() )

	with sh.function("test_ddx_fine_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.ddx_fine() )

	with sh.function("test_ddx_fine_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.ddx_fine() )

	with sh.function("test_ddx_fine_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.ddx_fine() )

	with sh.function("test_ddx_fine_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.ddx_fine() )

	with sh.function("test_ddx_fine_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.ddx_fine() )

	with sh.function("test_ddx_fine_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.ddx_fine() )

	with sh.function("test_ddx_fine_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.ddx_fine() )

	with sh.function("test_ddx_fine_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.ddx_fine() )

	with sh.function("test_ddx_fine_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.ddx_fine() )

	with sh.function("test_ddy_Float", sh.Float)():
		sh.return_( sh.g_f.ddy() )

	with sh.function("test_ddy_Float1", sh.Float1)():
		sh.return_( sh.g_f1.ddy() )

	with sh.function("test_ddy_Float2", sh.Float2)():
		sh.return_( sh.g_f2.ddy() )

	with sh.function("test_ddy_Float3", sh.Float3)():
		sh.return_( sh.g_f3.ddy() )

	with sh.function("test_ddy_Float4", sh.Float4)():
		sh.return_( sh.g_f4.ddy() )

	with sh.function("test_ddy_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.ddy() )

	with sh.function("test_ddy_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.ddy() )

	with sh.function("test_ddy_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.ddy() )

	with sh.function("test_ddy_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.ddy() )

	with sh.function("test_ddy_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.ddy() )

	with sh.function("test_ddy_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.ddy() )

	with sh.function("test_ddy_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.ddy() )

	with sh.function("test_ddy_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.ddy() )

	with sh.function("test_ddy_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.ddy() )

	with sh.function("test_ddy_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.ddy() )

	with sh.function("test_ddy_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.ddy() )

	with sh.function("test_ddy_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.ddy() )

	with sh.function("test_ddy_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.ddy() )

	with sh.function("test_ddy_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.ddy() )

	with sh.function("test_ddy_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.ddy() )

	with sh.function("test_ddy_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.ddy() )

	with sh.function("test_ddy_coarse_Float", sh.Float)():
		sh.return_( sh.g_f.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float1", sh.Float1)():
		sh.return_( sh.g_f1.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float2", sh.Float2)():
		sh.return_( sh.g_f2.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float3", sh.Float3)():
		sh.return_( sh.g_f3.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float4", sh.Float4)():
		sh.return_( sh.g_f4.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.ddy_coarse() )

	with sh.function("test_ddy_coarse_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.ddy_coarse() )

	with sh.function("test_ddy_fine_Float", sh.Float)():
		sh.return_( sh.g_f.ddy_fine() )

	with sh.function("test_ddy_fine_Float1", sh.Float1)():
		sh.return_( sh.g_f1.ddy_fine() )

	with sh.function("test_ddy_fine_Float2", sh.Float2)():
		sh.return_( sh.g_f2.ddy_fine() )

	with sh.function("test_ddy_fine_Float3", sh.Float3)():
		sh.return_( sh.g_f3.ddy_fine() )

	with sh.function("test_ddy_fine_Float4", sh.Float4)():
		sh.return_( sh.g_f4.ddy_fine() )

	with sh.function("test_ddy_fine_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.ddy_fine() )

	with sh.function("test_ddy_fine_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.ddy_fine() )

	with sh.function("test_ddy_fine_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.ddy_fine() )

	with sh.function("test_ddy_fine_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.ddy_fine() )

	with sh.function("test_ddy_fine_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.ddy_fine() )

	with sh.function("test_ddy_fine_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.ddy_fine() )

	with sh.function("test_ddy_fine_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.ddy_fine() )

	with sh.function("test_ddy_fine_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.ddy_fine() )

	with sh.function("test_ddy_fine_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.ddy_fine() )

	with sh.function("test_ddy_fine_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.ddy_fine() )

	with sh.function("test_ddy_fine_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.ddy_fine() )

	with sh.function("test_ddy_fine_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.ddy_fine() )

	with sh.function("test_ddy_fine_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.ddy_fine() )

	with sh.function("test_ddy_fine_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.ddy_fine() )

	with sh.function("test_ddy_fine_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.ddy_fine() )

	with sh.function("test_ddy_fine_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.ddy_fine() )

	with sh.function("test_degrees_Float", sh.Float)():
		sh.return_( sh.g_f.degrees() )

	with sh.function("test_degrees_Float1", sh.Float1)():
		sh.return_( sh.g_f1.degrees() )

	with sh.function("test_degrees_Float2", sh.Float2)():
		sh.return_( sh.g_f2.degrees() )

	with sh.function("test_degrees_Float3", sh.Float3)():
		sh.return_( sh.g_f3.degrees() )

	with sh.function("test_degrees_Float4", sh.Float4)():
		sh.return_( sh.g_f4.degrees() )

	with sh.function("test_degrees_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.degrees() )

	with sh.function("test_degrees_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.degrees() )

	with sh.function("test_degrees_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.degrees() )

	with sh.function("test_degrees_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.degrees() )

	with sh.function("test_degrees_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.degrees() )

	with sh.function("test_degrees_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.degrees() )

	with sh.function("test_degrees_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.degrees() )

	with sh.function("test_degrees_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.degrees() )

	with sh.function("test_degrees_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.degrees() )

	with sh.function("test_degrees_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.degrees() )

	with sh.function("test_degrees_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.degrees() )

	with sh.function("test_degrees_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.degrees() )

	with sh.function("test_degrees_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.degrees() )

	with sh.function("test_degrees_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.degrees() )

	with sh.function("test_degrees_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.degrees() )

	with sh.function("test_degrees_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.degrees() )

	with sh.function("test_exp_Float", sh.Float)():
		sh.return_( sh.g_f.exp() )

	with sh.function("test_exp_Float1", sh.Float1)():
		sh.return_( sh.g_f1.exp() )

	with sh.function("test_exp_Float2", sh.Float2)():
		sh.return_( sh.g_f2.exp() )

	with sh.function("test_exp_Float3", sh.Float3)():
		sh.return_( sh.g_f3.exp() )

	with sh.function("test_exp_Float4", sh.Float4)():
		sh.return_( sh.g_f4.exp() )

	with sh.function("test_exp_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.exp() )

	with sh.function("test_exp_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.exp() )

	with sh.function("test_exp_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.exp() )

	with sh.function("test_exp_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.exp() )

	with sh.function("test_exp_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.exp() )

	with sh.function("test_exp_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.exp() )

	with sh.function("test_exp_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.exp() )

	with sh.function("test_exp_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.exp() )

	with sh.function("test_exp_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.exp() )

	with sh.function("test_exp_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.exp() )

	with sh.function("test_exp_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.exp() )

	with sh.function("test_exp_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.exp() )

	with sh.function("test_exp_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.exp() )

	with sh.function("test_exp_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.exp() )

	with sh.function("test_exp_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.exp() )

	with sh.function("test_exp_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.exp() )

	with sh.function("test_exp2_Float", sh.Float)():
		sh.return_( sh.g_f.exp2() )

	with sh.function("test_exp2_Float1", sh.Float1)():
		sh.return_( sh.g_f1.exp2() )

	with sh.function("test_exp2_Float2", sh.Float2)():
		sh.return_( sh.g_f2.exp2() )

	with sh.function("test_exp2_Float3", sh.Float3)():
		sh.return_( sh.g_f3.exp2() )

	with sh.function("test_exp2_Float4", sh.Float4)():
		sh.return_( sh.g_f4.exp2() )

	with sh.function("test_exp2_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.exp2() )

	with sh.function("test_exp2_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.exp2() )

	with sh.function("test_exp2_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.exp2() )

	with sh.function("test_exp2_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.exp2() )

	with sh.function("test_exp2_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.exp2() )

	with sh.function("test_exp2_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.exp2() )

	with sh.function("test_exp2_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.exp2() )

	with sh.function("test_exp2_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.exp2() )

	with sh.function("test_exp2_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.exp2() )

	with sh.function("test_exp2_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.exp2() )

	with sh.function("test_exp2_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.exp2() )

	with sh.function("test_exp2_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.exp2() )

	with sh.function("test_exp2_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.exp2() )

	with sh.function("test_exp2_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.exp2() )

	with sh.function("test_exp2_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.exp2() )

	with sh.function("test_exp2_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.exp2() )

	with sh.function("test_floor_Float", sh.Float)():
		sh.return_( sh.g_f.floor() )

	with sh.function("test_floor_Float1", sh.Float1)():
		sh.return_( sh.g_f1.floor() )

	with sh.function("test_floor_Float2", sh.Float2)():
		sh.return_( sh.g_f2.floor() )

	with sh.function("test_floor_Float3", sh.Float3)():
		sh.return_( sh.g_f3.floor() )

	with sh.function("test_floor_Float4", sh.Float4)():
		sh.return_( sh.g_f4.floor() )

	with sh.function("test_floor_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.floor() )

	with sh.function("test_floor_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.floor() )

	with sh.function("test_floor_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.floor() )

	with sh.function("test_floor_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.floor() )

	with sh.function("test_floor_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.floor() )

	with sh.function("test_floor_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.floor() )

	with sh.function("test_floor_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.floor() )

	with sh.function("test_floor_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.floor() )

	with sh.function("test_floor_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.floor() )

	with sh.function("test_floor_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.floor() )

	with sh.function("test_floor_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.floor() )

	with sh.function("test_floor_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.floor() )

	with sh.function("test_floor_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.floor() )

	with sh.function("test_floor_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.floor() )

	with sh.function("test_floor_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.floor() )

	with sh.function("test_floor_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.floor() )

	with sh.function("test_fmod_Float", sh.Float)(b = sh.Float):
		sh.return_( sh.g_f.fmod(b = sh.b) )

	with sh.function("test_fmod_Float1", sh.Float1)(b = sh.Float1):
		sh.return_( sh.g_f1.fmod(b = sh.b) )

	with sh.function("test_fmod_Float2", sh.Float2)(b = sh.Float2):
		sh.return_( sh.g_f2.fmod(b = sh.b) )

	with sh.function("test_fmod_Float3", sh.Float3)(b = sh.Float3):
		sh.return_( sh.g_f3.fmod(b = sh.b) )

	with sh.function("test_fmod_Float4", sh.Float4)(b = sh.Float4):
		sh.return_( sh.g_f4.fmod(b = sh.b) )

	with sh.function("test_fmod_Float1x1", sh.Float1x1)(b = sh.Float1x1):
		sh.return_( sh.g_f1x1.fmod(b = sh.b) )

	with sh.function("test_fmod_Float1x2", sh.Float1x2)(b = sh.Float1x2):
		sh.return_( sh.g_f1x2.fmod(b = sh.b) )

	with sh.function("test_fmod_Float1x3", sh.Float1x3)(b = sh.Float1x3):
		sh.return_( sh.g_f1x3.fmod(b = sh.b) )

	with sh.function("test_fmod_Float1x4", sh.Float1x4)(b = sh.Float1x4):
		sh.return_( sh.g_f1x4.fmod(b = sh.b) )

	with sh.function("test_fmod_Float2x1", sh.Float2x1)(b = sh.Float2x1):
		sh.return_( sh.g_f2x1.fmod(b = sh.b) )

	with sh.function("test_fmod_Float2x2", sh.Float2x2)(b = sh.Float2x2):
		sh.return_( sh.g_f2x2.fmod(b = sh.b) )

	with sh.function("test_fmod_Float2x3", sh.Float2x3)(b = sh.Float2x3):
		sh.return_( sh.g_f2x3.fmod(b = sh.b) )

	with sh.function("test_fmod_Float2x4", sh.Float2x4)(b = sh.Float2x4):
		sh.return_( sh.g_f2x4.fmod(b = sh.b) )

	with sh.function("test_fmod_Float3x1", sh.Float3x1)(b = sh.Float3x1):
		sh.return_( sh.g_f3x1.fmod(b = sh.b) )

	with sh.function("test_fmod_Float3x2", sh.Float3x2)(b = sh.Float3x2):
		sh.return_( sh.g_f3x2.fmod(b = sh.b) )

	with sh.function("test_fmod_Float3x3", sh.Float3x3)(b = sh.Float3x3):
		sh.return_( sh.g_f3x3.fmod(b = sh.b) )

	with sh.function("test_fmod_Float3x4", sh.Float3x4)(b = sh.Float3x4):
		sh.return_( sh.g_f3x4.fmod(b = sh.b) )

	with sh.function("test_fmod_Float4x1", sh.Float4x1)(b = sh.Float4x1):
		sh.return_( sh.g_f4x1.fmod(b = sh.b) )

	with sh.function("test_fmod_Float4x2", sh.Float4x2)(b = sh.Float4x2):
		sh.return_( sh.g_f4x2.fmod(b = sh.b) )

	with sh.function("test_fmod_Float4x3", sh.Float4x3)(b = sh.Float4x3):
		sh.return_( sh.g_f4x3.fmod(b = sh.b) )

	with sh.function("test_fmod_Float4x4", sh.Float4x4)(b = sh.Float4x4):
		sh.return_( sh.g_f4x4.fmod(b = sh.b) )

	with sh.function("test_frac_Float", sh.Float)():
		sh.return_( sh.g_f.frac() )

	with sh.function("test_frac_Float1", sh.Float1)():
		sh.return_( sh.g_f1.frac() )

	with sh.function("test_frac_Float2", sh.Float2)():
		sh.return_( sh.g_f2.frac() )

	with sh.function("test_frac_Float3", sh.Float3)():
		sh.return_( sh.g_f3.frac() )

	with sh.function("test_frac_Float4", sh.Float4)():
		sh.return_( sh.g_f4.frac() )

	with sh.function("test_frac_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.frac() )

	with sh.function("test_frac_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.frac() )

	with sh.function("test_frac_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.frac() )

	with sh.function("test_frac_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.frac() )

	with sh.function("test_frac_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.frac() )

	with sh.function("test_frac_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.frac() )

	with sh.function("test_frac_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.frac() )

	with sh.function("test_frac_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.frac() )

	with sh.function("test_frac_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.frac() )

	with sh.function("test_frac_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.frac() )

	with sh.function("test_frac_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.frac() )

	with sh.function("test_frac_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.frac() )

	with sh.function("test_frac_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.frac() )

	with sh.function("test_frac_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.frac() )

	with sh.function("test_frac_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.frac() )

	with sh.function("test_frac_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.frac() )

	with sh.function("test_frexp_Float", sh.Float)(exp = sh.Float):
		sh.return_( sh.g_f.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float1", sh.Float1)(exp = sh.Float1):
		sh.return_( sh.g_f1.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float2", sh.Float2)(exp = sh.Float2):
		sh.return_( sh.g_f2.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float3", sh.Float3)(exp = sh.Float3):
		sh.return_( sh.g_f3.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float4", sh.Float4)(exp = sh.Float4):
		sh.return_( sh.g_f4.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float1x1", sh.Float1x1)(exp = sh.Float1x1):
		sh.return_( sh.g_f1x1.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float1x2", sh.Float1x2)(exp = sh.Float1x2):
		sh.return_( sh.g_f1x2.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float1x3", sh.Float1x3)(exp = sh.Float1x3):
		sh.return_( sh.g_f1x3.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float1x4", sh.Float1x4)(exp = sh.Float1x4):
		sh.return_( sh.g_f1x4.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float2x1", sh.Float2x1)(exp = sh.Float2x1):
		sh.return_( sh.g_f2x1.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float2x2", sh.Float2x2)(exp = sh.Float2x2):
		sh.return_( sh.g_f2x2.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float2x3", sh.Float2x3)(exp = sh.Float2x3):
		sh.return_( sh.g_f2x3.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float2x4", sh.Float2x4)(exp = sh.Float2x4):
		sh.return_( sh.g_f2x4.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float3x1", sh.Float3x1)(exp = sh.Float3x1):
		sh.return_( sh.g_f3x1.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float3x2", sh.Float3x2)(exp = sh.Float3x2):
		sh.return_( sh.g_f3x2.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float3x3", sh.Float3x3)(exp = sh.Float3x3):
		sh.return_( sh.g_f3x3.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float3x4", sh.Float3x4)(exp = sh.Float3x4):
		sh.return_( sh.g_f3x4.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float4x1", sh.Float4x1)(exp = sh.Float4x1):
		sh.return_( sh.g_f4x1.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float4x2", sh.Float4x2)(exp = sh.Float4x2):
		sh.return_( sh.g_f4x2.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float4x3", sh.Float4x3)(exp = sh.Float4x3):
		sh.return_( sh.g_f4x3.frexp(exp = sh.exp) )

	with sh.function("test_frexp_Float4x4", sh.Float4x4)(exp = sh.Float4x4):
		sh.return_( sh.g_f4x4.frexp(exp = sh.exp) )

	with sh.function("test_fwidth_Float", sh.Float)():
		sh.return_( sh.g_f.fwidth() )

	with sh.function("test_fwidth_Float1", sh.Float1)():
		sh.return_( sh.g_f1.fwidth() )

	with sh.function("test_fwidth_Float2", sh.Float2)():
		sh.return_( sh.g_f2.fwidth() )

	with sh.function("test_fwidth_Float3", sh.Float3)():
		sh.return_( sh.g_f3.fwidth() )

	with sh.function("test_fwidth_Float4", sh.Float4)():
		sh.return_( sh.g_f4.fwidth() )

	with sh.function("test_fwidth_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.fwidth() )

	with sh.function("test_fwidth_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.fwidth() )

	with sh.function("test_fwidth_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.fwidth() )

	with sh.function("test_fwidth_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.fwidth() )

	with sh.function("test_fwidth_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.fwidth() )

	with sh.function("test_fwidth_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.fwidth() )

	with sh.function("test_fwidth_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.fwidth() )

	with sh.function("test_fwidth_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.fwidth() )

	with sh.function("test_fwidth_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.fwidth() )

	with sh.function("test_fwidth_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.fwidth() )

	with sh.function("test_fwidth_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.fwidth() )

	with sh.function("test_fwidth_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.fwidth() )

	with sh.function("test_fwidth_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.fwidth() )

	with sh.function("test_fwidth_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.fwidth() )

	with sh.function("test_fwidth_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.fwidth() )

	with sh.function("test_fwidth_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.fwidth() )

	with sh.function("test_ldexp_Float", sh.Float)(exp = sh.Float):
		sh.return_( sh.g_f.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float1", sh.Float1)(exp = sh.Float1):
		sh.return_( sh.g_f1.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float2", sh.Float2)(exp = sh.Float2):
		sh.return_( sh.g_f2.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float3", sh.Float3)(exp = sh.Float3):
		sh.return_( sh.g_f3.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float4", sh.Float4)(exp = sh.Float4):
		sh.return_( sh.g_f4.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float1x1", sh.Float1x1)(exp = sh.Float1x1):
		sh.return_( sh.g_f1x1.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float1x2", sh.Float1x2)(exp = sh.Float1x2):
		sh.return_( sh.g_f1x2.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float1x3", sh.Float1x3)(exp = sh.Float1x3):
		sh.return_( sh.g_f1x3.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float1x4", sh.Float1x4)(exp = sh.Float1x4):
		sh.return_( sh.g_f1x4.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float2x1", sh.Float2x1)(exp = sh.Float2x1):
		sh.return_( sh.g_f2x1.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float2x2", sh.Float2x2)(exp = sh.Float2x2):
		sh.return_( sh.g_f2x2.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float2x3", sh.Float2x3)(exp = sh.Float2x3):
		sh.return_( sh.g_f2x3.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float2x4", sh.Float2x4)(exp = sh.Float2x4):
		sh.return_( sh.g_f2x4.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float3x1", sh.Float3x1)(exp = sh.Float3x1):
		sh.return_( sh.g_f3x1.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float3x2", sh.Float3x2)(exp = sh.Float3x2):
		sh.return_( sh.g_f3x2.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float3x3", sh.Float3x3)(exp = sh.Float3x3):
		sh.return_( sh.g_f3x3.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float3x4", sh.Float3x4)(exp = sh.Float3x4):
		sh.return_( sh.g_f3x4.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float4x1", sh.Float4x1)(exp = sh.Float4x1):
		sh.return_( sh.g_f4x1.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float4x2", sh.Float4x2)(exp = sh.Float4x2):
		sh.return_( sh.g_f4x2.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float4x3", sh.Float4x3)(exp = sh.Float4x3):
		sh.return_( sh.g_f4x3.ldexp(exp = sh.exp) )

	with sh.function("test_ldexp_Float4x4", sh.Float4x4)(exp = sh.Float4x4):
		sh.return_( sh.g_f4x4.ldexp(exp = sh.exp) )

	with sh.function("test_lerp_Float", sh.Float)(a = sh.Float, b = sh.Float):
		sh.return_( sh.g_f.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float1", sh.Float1)(a = sh.Float1, b = sh.Float1):
		sh.return_( sh.g_f1.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float2", sh.Float2)(a = sh.Float2, b = sh.Float2):
		sh.return_( sh.g_f2.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float3", sh.Float3)(a = sh.Float3, b = sh.Float3):
		sh.return_( sh.g_f3.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float4", sh.Float4)(a = sh.Float4, b = sh.Float4):
		sh.return_( sh.g_f4.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float1x1", sh.Float1x1)(a = sh.Float1x1, b = sh.Float1x1):
		sh.return_( sh.g_f1x1.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float1x2", sh.Float1x2)(a = sh.Float1x2, b = sh.Float1x2):
		sh.return_( sh.g_f1x2.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float1x3", sh.Float1x3)(a = sh.Float1x3, b = sh.Float1x3):
		sh.return_( sh.g_f1x3.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float1x4", sh.Float1x4)(a = sh.Float1x4, b = sh.Float1x4):
		sh.return_( sh.g_f1x4.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float2x1", sh.Float2x1)(a = sh.Float2x1, b = sh.Float2x1):
		sh.return_( sh.g_f2x1.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float2x2", sh.Float2x2)(a = sh.Float2x2, b = sh.Float2x2):
		sh.return_( sh.g_f2x2.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float2x3", sh.Float2x3)(a = sh.Float2x3, b = sh.Float2x3):
		sh.return_( sh.g_f2x3.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float2x4", sh.Float2x4)(a = sh.Float2x4, b = sh.Float2x4):
		sh.return_( sh.g_f2x4.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float3x1", sh.Float3x1)(a = sh.Float3x1, b = sh.Float3x1):
		sh.return_( sh.g_f3x1.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float3x2", sh.Float3x2)(a = sh.Float3x2, b = sh.Float3x2):
		sh.return_( sh.g_f3x2.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float3x3", sh.Float3x3)(a = sh.Float3x3, b = sh.Float3x3):
		sh.return_( sh.g_f3x3.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float3x4", sh.Float3x4)(a = sh.Float3x4, b = sh.Float3x4):
		sh.return_( sh.g_f3x4.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float4x1", sh.Float4x1)(a = sh.Float4x1, b = sh.Float4x1):
		sh.return_( sh.g_f4x1.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float4x2", sh.Float4x2)(a = sh.Float4x2, b = sh.Float4x2):
		sh.return_( sh.g_f4x2.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float4x3", sh.Float4x3)(a = sh.Float4x3, b = sh.Float4x3):
		sh.return_( sh.g_f4x3.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_lerp_Float4x4", sh.Float4x4)(a = sh.Float4x4, b = sh.Float4x4):
		sh.return_( sh.g_f4x4.lerp(a = sh.a, b = sh.b) )

	with sh.function("test_log_Float", sh.Float)():
		sh.return_( sh.g_f.log() )

	with sh.function("test_log_Float1", sh.Float1)():
		sh.return_( sh.g_f1.log() )

	with sh.function("test_log_Float2", sh.Float2)():
		sh.return_( sh.g_f2.log() )

	with sh.function("test_log_Float3", sh.Float3)():
		sh.return_( sh.g_f3.log() )

	with sh.function("test_log_Float4", sh.Float4)():
		sh.return_( sh.g_f4.log() )

	with sh.function("test_log_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.log() )

	with sh.function("test_log_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.log() )

	with sh.function("test_log_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.log() )

	with sh.function("test_log_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.log() )

	with sh.function("test_log_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.log() )

	with sh.function("test_log_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.log() )

	with sh.function("test_log_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.log() )

	with sh.function("test_log_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.log() )

	with sh.function("test_log_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.log() )

	with sh.function("test_log_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.log() )

	with sh.function("test_log_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.log() )

	with sh.function("test_log_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.log() )

	with sh.function("test_log_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.log() )

	with sh.function("test_log_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.log() )

	with sh.function("test_log_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.log() )

	with sh.function("test_log_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.log() )

	with sh.function("test_log10_Float", sh.Float)():
		sh.return_( sh.g_f.log10() )

	with sh.function("test_log10_Float1", sh.Float1)():
		sh.return_( sh.g_f1.log10() )

	with sh.function("test_log10_Float2", sh.Float2)():
		sh.return_( sh.g_f2.log10() )

	with sh.function("test_log10_Float3", sh.Float3)():
		sh.return_( sh.g_f3.log10() )

	with sh.function("test_log10_Float4", sh.Float4)():
		sh.return_( sh.g_f4.log10() )

	with sh.function("test_log10_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.log10() )

	with sh.function("test_log10_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.log10() )

	with sh.function("test_log10_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.log10() )

	with sh.function("test_log10_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.log10() )

	with sh.function("test_log10_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.log10() )

	with sh.function("test_log10_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.log10() )

	with sh.function("test_log10_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.log10() )

	with sh.function("test_log10_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.log10() )

	with sh.function("test_log10_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.log10() )

	with sh.function("test_log10_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.log10() )

	with sh.function("test_log10_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.log10() )

	with sh.function("test_log10_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.log10() )

	with sh.function("test_log10_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.log10() )

	with sh.function("test_log10_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.log10() )

	with sh.function("test_log10_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.log10() )

	with sh.function("test_log10_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.log10() )

	with sh.function("test_log2_Float", sh.Float)():
		sh.return_( sh.g_f.log2() )

	with sh.function("test_log2_Float1", sh.Float1)():
		sh.return_( sh.g_f1.log2() )

	with sh.function("test_log2_Float2", sh.Float2)():
		sh.return_( sh.g_f2.log2() )

	with sh.function("test_log2_Float3", sh.Float3)():
		sh.return_( sh.g_f3.log2() )

	with sh.function("test_log2_Float4", sh.Float4)():
		sh.return_( sh.g_f4.log2() )

	with sh.function("test_log2_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.log2() )

	with sh.function("test_log2_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.log2() )

	with sh.function("test_log2_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.log2() )

	with sh.function("test_log2_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.log2() )

	with sh.function("test_log2_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.log2() )

	with sh.function("test_log2_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.log2() )

	with sh.function("test_log2_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.log2() )

	with sh.function("test_log2_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.log2() )

	with sh.function("test_log2_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.log2() )

	with sh.function("test_log2_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.log2() )

	with sh.function("test_log2_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.log2() )

	with sh.function("test_log2_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.log2() )

	with sh.function("test_log2_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.log2() )

	with sh.function("test_log2_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.log2() )

	with sh.function("test_log2_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.log2() )

	with sh.function("test_log2_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.log2() )

	with sh.function("test_modf_Float", sh.Float)(ip = sh.Float):
		sh.return_( sh.g_f.modf(ip = sh.ip) )

	with sh.function("test_modf_Float1", sh.Float1)(ip = sh.Float1):
		sh.return_( sh.g_f1.modf(ip = sh.ip) )

	with sh.function("test_modf_Float2", sh.Float2)(ip = sh.Float2):
		sh.return_( sh.g_f2.modf(ip = sh.ip) )

	with sh.function("test_modf_Float3", sh.Float3)(ip = sh.Float3):
		sh.return_( sh.g_f3.modf(ip = sh.ip) )

	with sh.function("test_modf_Float4", sh.Float4)(ip = sh.Float4):
		sh.return_( sh.g_f4.modf(ip = sh.ip) )

	with sh.function("test_modf_Float1x1", sh.Float1x1)(ip = sh.Float1x1):
		sh.return_( sh.g_f1x1.modf(ip = sh.ip) )

	with sh.function("test_modf_Float1x2", sh.Float1x2)(ip = sh.Float1x2):
		sh.return_( sh.g_f1x2.modf(ip = sh.ip) )

	with sh.function("test_modf_Float1x3", sh.Float1x3)(ip = sh.Float1x3):
		sh.return_( sh.g_f1x3.modf(ip = sh.ip) )

	with sh.function("test_modf_Float1x4", sh.Float1x4)(ip = sh.Float1x4):
		sh.return_( sh.g_f1x4.modf(ip = sh.ip) )

	with sh.function("test_modf_Float2x1", sh.Float2x1)(ip = sh.Float2x1):
		sh.return_( sh.g_f2x1.modf(ip = sh.ip) )

	with sh.function("test_modf_Float2x2", sh.Float2x2)(ip = sh.Float2x2):
		sh.return_( sh.g_f2x2.modf(ip = sh.ip) )

	with sh.function("test_modf_Float2x3", sh.Float2x3)(ip = sh.Float2x3):
		sh.return_( sh.g_f2x3.modf(ip = sh.ip) )

	with sh.function("test_modf_Float2x4", sh.Float2x4)(ip = sh.Float2x4):
		sh.return_( sh.g_f2x4.modf(ip = sh.ip) )

	with sh.function("test_modf_Float3x1", sh.Float3x1)(ip = sh.Float3x1):
		sh.return_( sh.g_f3x1.modf(ip = sh.ip) )

	with sh.function("test_modf_Float3x2", sh.Float3x2)(ip = sh.Float3x2):
		sh.return_( sh.g_f3x2.modf(ip = sh.ip) )

	with sh.function("test_modf_Float3x3", sh.Float3x3)(ip = sh.Float3x3):
		sh.return_( sh.g_f3x3.modf(ip = sh.ip) )

	with sh.function("test_modf_Float3x4", sh.Float3x4)(ip = sh.Float3x4):
		sh.return_( sh.g_f3x4.modf(ip = sh.ip) )

	with sh.function("test_modf_Float4x1", sh.Float4x1)(ip = sh.Float4x1):
		sh.return_( sh.g_f4x1.modf(ip = sh.ip) )

	with sh.function("test_modf_Float4x2", sh.Float4x2)(ip = sh.Float4x2):
		sh.return_( sh.g_f4x2.modf(ip = sh.ip) )

	with sh.function("test_modf_Float4x3", sh.Float4x3)(ip = sh.Float4x3):
		sh.return_( sh.g_f4x3.modf(ip = sh.ip) )

	with sh.function("test_modf_Float4x4", sh.Float4x4)(ip = sh.Float4x4):
		sh.return_( sh.g_f4x4.modf(ip = sh.ip) )

	with sh.function("test_pow_Float", sh.Float)(y = sh.Float):
		sh.return_( sh.g_f.pow(y = sh.y) )

	with sh.function("test_pow_Float1", sh.Float1)(y = sh.Float1):
		sh.return_( sh.g_f1.pow(y = sh.y) )

	with sh.function("test_pow_Float2", sh.Float2)(y = sh.Float2):
		sh.return_( sh.g_f2.pow(y = sh.y) )

	with sh.function("test_pow_Float3", sh.Float3)(y = sh.Float3):
		sh.return_( sh.g_f3.pow(y = sh.y) )

	with sh.function("test_pow_Float4", sh.Float4)(y = sh.Float4):
		sh.return_( sh.g_f4.pow(y = sh.y) )

	with sh.function("test_pow_Float1x1", sh.Float1x1)(y = sh.Float1x1):
		sh.return_( sh.g_f1x1.pow(y = sh.y) )

	with sh.function("test_pow_Float1x2", sh.Float1x2)(y = sh.Float1x2):
		sh.return_( sh.g_f1x2.pow(y = sh.y) )

	with sh.function("test_pow_Float1x3", sh.Float1x3)(y = sh.Float1x3):
		sh.return_( sh.g_f1x3.pow(y = sh.y) )

	with sh.function("test_pow_Float1x4", sh.Float1x4)(y = sh.Float1x4):
		sh.return_( sh.g_f1x4.pow(y = sh.y) )

	with sh.function("test_pow_Float2x1", sh.Float2x1)(y = sh.Float2x1):
		sh.return_( sh.g_f2x1.pow(y = sh.y) )

	with sh.function("test_pow_Float2x2", sh.Float2x2)(y = sh.Float2x2):
		sh.return_( sh.g_f2x2.pow(y = sh.y) )

	with sh.function("test_pow_Float2x3", sh.Float2x3)(y = sh.Float2x3):
		sh.return_( sh.g_f2x3.pow(y = sh.y) )

	with sh.function("test_pow_Float2x4", sh.Float2x4)(y = sh.Float2x4):
		sh.return_( sh.g_f2x4.pow(y = sh.y) )

	with sh.function("test_pow_Float3x1", sh.Float3x1)(y = sh.Float3x1):
		sh.return_( sh.g_f3x1.pow(y = sh.y) )

	with sh.function("test_pow_Float3x2", sh.Float3x2)(y = sh.Float3x2):
		sh.return_( sh.g_f3x2.pow(y = sh.y) )

	with sh.function("test_pow_Float3x3", sh.Float3x3)(y = sh.Float3x3):
		sh.return_( sh.g_f3x3.pow(y = sh.y) )

	with sh.function("test_pow_Float3x4", sh.Float3x4)(y = sh.Float3x4):
		sh.return_( sh.g_f3x4.pow(y = sh.y) )

	with sh.function("test_pow_Float4x1", sh.Float4x1)(y = sh.Float4x1):
		sh.return_( sh.g_f4x1.pow(y = sh.y) )

	with sh.function("test_pow_Float4x2", sh.Float4x2)(y = sh.Float4x2):
		sh.return_( sh.g_f4x2.pow(y = sh.y) )

	with sh.function("test_pow_Float4x3", sh.Float4x3)(y = sh.Float4x3):
		sh.return_( sh.g_f4x3.pow(y = sh.y) )

	with sh.function("test_pow_Float4x4", sh.Float4x4)(y = sh.Float4x4):
		sh.return_( sh.g_f4x4.pow(y = sh.y) )

	with sh.function("test_radians_Float", sh.Float)():
		sh.return_( sh.g_f.radians() )

	with sh.function("test_radians_Float1", sh.Float1)():
		sh.return_( sh.g_f1.radians() )

	with sh.function("test_radians_Float2", sh.Float2)():
		sh.return_( sh.g_f2.radians() )

	with sh.function("test_radians_Float3", sh.Float3)():
		sh.return_( sh.g_f3.radians() )

	with sh.function("test_radians_Float4", sh.Float4)():
		sh.return_( sh.g_f4.radians() )

	with sh.function("test_radians_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.radians() )

	with sh.function("test_radians_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.radians() )

	with sh.function("test_radians_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.radians() )

	with sh.function("test_radians_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.radians() )

	with sh.function("test_radians_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.radians() )

	with sh.function("test_radians_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.radians() )

	with sh.function("test_radians_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.radians() )

	with sh.function("test_radians_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.radians() )

	with sh.function("test_radians_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.radians() )

	with sh.function("test_radians_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.radians() )

	with sh.function("test_radians_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.radians() )

	with sh.function("test_radians_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.radians() )

	with sh.function("test_radians_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.radians() )

	with sh.function("test_radians_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.radians() )

	with sh.function("test_radians_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.radians() )

	with sh.function("test_radians_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.radians() )

	with sh.function("test_rcp_Float", sh.Float)():
		sh.return_( sh.g_f.rcp() )

	with sh.function("test_rcp_Float1", sh.Float1)():
		sh.return_( sh.g_f1.rcp() )

	with sh.function("test_rcp_Float2", sh.Float2)():
		sh.return_( sh.g_f2.rcp() )

	with sh.function("test_rcp_Float3", sh.Float3)():
		sh.return_( sh.g_f3.rcp() )

	with sh.function("test_rcp_Float4", sh.Float4)():
		sh.return_( sh.g_f4.rcp() )

	with sh.function("test_rcp_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.rcp() )

	with sh.function("test_rcp_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.rcp() )

	with sh.function("test_rcp_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.rcp() )

	with sh.function("test_rcp_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.rcp() )

	with sh.function("test_rcp_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.rcp() )

	with sh.function("test_rcp_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.rcp() )

	with sh.function("test_rcp_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.rcp() )

	with sh.function("test_rcp_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.rcp() )

	with sh.function("test_rcp_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.rcp() )

	with sh.function("test_rcp_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.rcp() )

	with sh.function("test_rcp_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.rcp() )

	with sh.function("test_rcp_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.rcp() )

	with sh.function("test_rcp_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.rcp() )

	with sh.function("test_rcp_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.rcp() )

	with sh.function("test_rcp_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.rcp() )

	with sh.function("test_rcp_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.rcp() )

	with sh.function("test_round_Float", sh.Float)():
		sh.return_( sh.g_f.round() )

	with sh.function("test_round_Float1", sh.Float1)():
		sh.return_( sh.g_f1.round() )

	with sh.function("test_round_Float2", sh.Float2)():
		sh.return_( sh.g_f2.round() )

	with sh.function("test_round_Float3", sh.Float3)():
		sh.return_( sh.g_f3.round() )

	with sh.function("test_round_Float4", sh.Float4)():
		sh.return_( sh.g_f4.round() )

	with sh.function("test_round_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.round() )

	with sh.function("test_round_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.round() )

	with sh.function("test_round_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.round() )

	with sh.function("test_round_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.round() )

	with sh.function("test_round_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.round() )

	with sh.function("test_round_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.round() )

	with sh.function("test_round_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.round() )

	with sh.function("test_round_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.round() )

	with sh.function("test_round_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.round() )

	with sh.function("test_round_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.round() )

	with sh.function("test_round_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.round() )

	with sh.function("test_round_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.round() )

	with sh.function("test_round_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.round() )

	with sh.function("test_round_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.round() )

	with sh.function("test_round_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.round() )

	with sh.function("test_round_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.round() )

	with sh.function("test_rsqrt_Float", sh.Float)():
		sh.return_( sh.g_f.rsqrt() )

	with sh.function("test_rsqrt_Float1", sh.Float1)():
		sh.return_( sh.g_f1.rsqrt() )

	with sh.function("test_rsqrt_Float2", sh.Float2)():
		sh.return_( sh.g_f2.rsqrt() )

	with sh.function("test_rsqrt_Float3", sh.Float3)():
		sh.return_( sh.g_f3.rsqrt() )

	with sh.function("test_rsqrt_Float4", sh.Float4)():
		sh.return_( sh.g_f4.rsqrt() )

	with sh.function("test_rsqrt_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.rsqrt() )

	with sh.function("test_rsqrt_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.rsqrt() )

	with sh.function("test_rsqrt_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.rsqrt() )

	with sh.function("test_rsqrt_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.rsqrt() )

	with sh.function("test_rsqrt_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.rsqrt() )

	with sh.function("test_rsqrt_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.rsqrt() )

	with sh.function("test_rsqrt_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.rsqrt() )

	with sh.function("test_rsqrt_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.rsqrt() )

	with sh.function("test_rsqrt_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.rsqrt() )

	with sh.function("test_rsqrt_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.rsqrt() )

	with sh.function("test_rsqrt_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.rsqrt() )

	with sh.function("test_rsqrt_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.rsqrt() )

	with sh.function("test_rsqrt_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.rsqrt() )

	with sh.function("test_rsqrt_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.rsqrt() )

	with sh.function("test_rsqrt_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.rsqrt() )

	with sh.function("test_rsqrt_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.rsqrt() )

	with sh.function("test_saturate_Float", sh.Float)():
		sh.return_( sh.g_f.saturate() )

	with sh.function("test_saturate_Float1", sh.Float1)():
		sh.return_( sh.g_f1.saturate() )

	with sh.function("test_saturate_Float2", sh.Float2)():
		sh.return_( sh.g_f2.saturate() )

	with sh.function("test_saturate_Float3", sh.Float3)():
		sh.return_( sh.g_f3.saturate() )

	with sh.function("test_saturate_Float4", sh.Float4)():
		sh.return_( sh.g_f4.saturate() )

	with sh.function("test_saturate_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.saturate() )

	with sh.function("test_saturate_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.saturate() )

	with sh.function("test_saturate_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.saturate() )

	with sh.function("test_saturate_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.saturate() )

	with sh.function("test_saturate_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.saturate() )

	with sh.function("test_saturate_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.saturate() )

	with sh.function("test_saturate_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.saturate() )

	with sh.function("test_saturate_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.saturate() )

	with sh.function("test_saturate_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.saturate() )

	with sh.function("test_saturate_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.saturate() )

	with sh.function("test_saturate_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.saturate() )

	with sh.function("test_saturate_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.saturate() )

	with sh.function("test_saturate_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.saturate() )

	with sh.function("test_saturate_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.saturate() )

	with sh.function("test_saturate_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.saturate() )

	with sh.function("test_saturate_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.saturate() )

	with sh.function("test_sin_Float", sh.Float)():
		sh.return_( sh.g_f.sin() )

	with sh.function("test_sin_Float1", sh.Float1)():
		sh.return_( sh.g_f1.sin() )

	with sh.function("test_sin_Float2", sh.Float2)():
		sh.return_( sh.g_f2.sin() )

	with sh.function("test_sin_Float3", sh.Float3)():
		sh.return_( sh.g_f3.sin() )

	with sh.function("test_sin_Float4", sh.Float4)():
		sh.return_( sh.g_f4.sin() )

	with sh.function("test_sin_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.sin() )

	with sh.function("test_sin_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.sin() )

	with sh.function("test_sin_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.sin() )

	with sh.function("test_sin_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.sin() )

	with sh.function("test_sin_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.sin() )

	with sh.function("test_sin_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.sin() )

	with sh.function("test_sin_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.sin() )

	with sh.function("test_sin_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.sin() )

	with sh.function("test_sin_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.sin() )

	with sh.function("test_sin_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.sin() )

	with sh.function("test_sin_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.sin() )

	with sh.function("test_sin_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.sin() )

	with sh.function("test_sin_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.sin() )

	with sh.function("test_sin_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.sin() )

	with sh.function("test_sin_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.sin() )

	with sh.function("test_sin_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.sin() )

	with sh.function("test_sincos_Float", None)(s = sh.Float, c = sh.Float):
		sh.g_f.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float1", None)(s = sh.Float1, c = sh.Float1):
		sh.g_f1.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float2", None)(s = sh.Float2, c = sh.Float2):
		sh.g_f2.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float3", None)(s = sh.Float3, c = sh.Float3):
		sh.g_f3.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float4", None)(s = sh.Float4, c = sh.Float4):
		sh.g_f4.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float1x1", None)(s = sh.Float1x1, c = sh.Float1x1):
		sh.g_f1x1.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float1x2", None)(s = sh.Float1x2, c = sh.Float1x2):
		sh.g_f1x2.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float1x3", None)(s = sh.Float1x3, c = sh.Float1x3):
		sh.g_f1x3.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float1x4", None)(s = sh.Float1x4, c = sh.Float1x4):
		sh.g_f1x4.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float2x1", None)(s = sh.Float2x1, c = sh.Float2x1):
		sh.g_f2x1.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float2x2", None)(s = sh.Float2x2, c = sh.Float2x2):
		sh.g_f2x2.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float2x3", None)(s = sh.Float2x3, c = sh.Float2x3):
		sh.g_f2x3.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float2x4", None)(s = sh.Float2x4, c = sh.Float2x4):
		sh.g_f2x4.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float3x1", None)(s = sh.Float3x1, c = sh.Float3x1):
		sh.g_f3x1.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float3x2", None)(s = sh.Float3x2, c = sh.Float3x2):
		sh.g_f3x2.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float3x3", None)(s = sh.Float3x3, c = sh.Float3x3):
		sh.g_f3x3.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float3x4", None)(s = sh.Float3x4, c = sh.Float3x4):
		sh.g_f3x4.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float4x1", None)(s = sh.Float4x1, c = sh.Float4x1):
		sh.g_f4x1.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float4x2", None)(s = sh.Float4x2, c = sh.Float4x2):
		sh.g_f4x2.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float4x3", None)(s = sh.Float4x3, c = sh.Float4x3):
		sh.g_f4x3.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sincos_Float4x4", None)(s = sh.Float4x4, c = sh.Float4x4):
		sh.g_f4x4.sincos(s = sh.s, c = sh.c)

	with sh.function("test_sinh_Float", sh.Float)():
		sh.return_( sh.g_f.sinh() )

	with sh.function("test_sinh_Float1", sh.Float1)():
		sh.return_( sh.g_f1.sinh() )

	with sh.function("test_sinh_Float2", sh.Float2)():
		sh.return_( sh.g_f2.sinh() )

	with sh.function("test_sinh_Float3", sh.Float3)():
		sh.return_( sh.g_f3.sinh() )

	with sh.function("test_sinh_Float4", sh.Float4)():
		sh.return_( sh.g_f4.sinh() )

	with sh.function("test_sinh_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.sinh() )

	with sh.function("test_sinh_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.sinh() )

	with sh.function("test_sinh_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.sinh() )

	with sh.function("test_sinh_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.sinh() )

	with sh.function("test_sinh_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.sinh() )

	with sh.function("test_sinh_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.sinh() )

	with sh.function("test_sinh_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.sinh() )

	with sh.function("test_sinh_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.sinh() )

	with sh.function("test_sinh_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.sinh() )

	with sh.function("test_sinh_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.sinh() )

	with sh.function("test_sinh_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.sinh() )

	with sh.function("test_sinh_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.sinh() )

	with sh.function("test_sinh_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.sinh() )

	with sh.function("test_sinh_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.sinh() )

	with sh.function("test_sinh_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.sinh() )

	with sh.function("test_sinh_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.sinh() )

	with sh.function("test_smoothstep_Float", sh.Float)(a = sh.Float, b = sh.Float):
		sh.return_( sh.g_f.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float1", sh.Float1)(a = sh.Float1, b = sh.Float1):
		sh.return_( sh.g_f1.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float2", sh.Float2)(a = sh.Float2, b = sh.Float2):
		sh.return_( sh.g_f2.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float3", sh.Float3)(a = sh.Float3, b = sh.Float3):
		sh.return_( sh.g_f3.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float4", sh.Float4)(a = sh.Float4, b = sh.Float4):
		sh.return_( sh.g_f4.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float1x1", sh.Float1x1)(a = sh.Float1x1, b = sh.Float1x1):
		sh.return_( sh.g_f1x1.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float1x2", sh.Float1x2)(a = sh.Float1x2, b = sh.Float1x2):
		sh.return_( sh.g_f1x2.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float1x3", sh.Float1x3)(a = sh.Float1x3, b = sh.Float1x3):
		sh.return_( sh.g_f1x3.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float1x4", sh.Float1x4)(a = sh.Float1x4, b = sh.Float1x4):
		sh.return_( sh.g_f1x4.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float2x1", sh.Float2x1)(a = sh.Float2x1, b = sh.Float2x1):
		sh.return_( sh.g_f2x1.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float2x2", sh.Float2x2)(a = sh.Float2x2, b = sh.Float2x2):
		sh.return_( sh.g_f2x2.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float2x3", sh.Float2x3)(a = sh.Float2x3, b = sh.Float2x3):
		sh.return_( sh.g_f2x3.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float2x4", sh.Float2x4)(a = sh.Float2x4, b = sh.Float2x4):
		sh.return_( sh.g_f2x4.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float3x1", sh.Float3x1)(a = sh.Float3x1, b = sh.Float3x1):
		sh.return_( sh.g_f3x1.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float3x2", sh.Float3x2)(a = sh.Float3x2, b = sh.Float3x2):
		sh.return_( sh.g_f3x2.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float3x3", sh.Float3x3)(a = sh.Float3x3, b = sh.Float3x3):
		sh.return_( sh.g_f3x3.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float3x4", sh.Float3x4)(a = sh.Float3x4, b = sh.Float3x4):
		sh.return_( sh.g_f3x4.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float4x1", sh.Float4x1)(a = sh.Float4x1, b = sh.Float4x1):
		sh.return_( sh.g_f4x1.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float4x2", sh.Float4x2)(a = sh.Float4x2, b = sh.Float4x2):
		sh.return_( sh.g_f4x2.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float4x3", sh.Float4x3)(a = sh.Float4x3, b = sh.Float4x3):
		sh.return_( sh.g_f4x3.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_smoothstep_Float4x4", sh.Float4x4)(a = sh.Float4x4, b = sh.Float4x4):
		sh.return_( sh.g_f4x4.smoothstep(a = sh.a, b = sh.b) )

	with sh.function("test_sqrt_Float", sh.Float)():
		sh.return_( sh.g_f.sqrt() )

	with sh.function("test_sqrt_Float1", sh.Float1)():
		sh.return_( sh.g_f1.sqrt() )

	with sh.function("test_sqrt_Float2", sh.Float2)():
		sh.return_( sh.g_f2.sqrt() )

	with sh.function("test_sqrt_Float3", sh.Float3)():
		sh.return_( sh.g_f3.sqrt() )

	with sh.function("test_sqrt_Float4", sh.Float4)():
		sh.return_( sh.g_f4.sqrt() )

	with sh.function("test_sqrt_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.sqrt() )

	with sh.function("test_sqrt_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.sqrt() )

	with sh.function("test_sqrt_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.sqrt() )

	with sh.function("test_sqrt_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.sqrt() )

	with sh.function("test_sqrt_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.sqrt() )

	with sh.function("test_sqrt_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.sqrt() )

	with sh.function("test_sqrt_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.sqrt() )

	with sh.function("test_sqrt_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.sqrt() )

	with sh.function("test_sqrt_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.sqrt() )

	with sh.function("test_sqrt_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.sqrt() )

	with sh.function("test_sqrt_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.sqrt() )

	with sh.function("test_sqrt_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.sqrt() )

	with sh.function("test_sqrt_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.sqrt() )

	with sh.function("test_sqrt_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.sqrt() )

	with sh.function("test_sqrt_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.sqrt() )

	with sh.function("test_sqrt_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.sqrt() )

	with sh.function("test_step_Float", sh.Float)(x = sh.Float):
		sh.return_( sh.g_f.step(x = sh.x) )

	with sh.function("test_step_Float1", sh.Float1)(x = sh.Float1):
		sh.return_( sh.g_f1.step(x = sh.x) )

	with sh.function("test_step_Float2", sh.Float2)(x = sh.Float2):
		sh.return_( sh.g_f2.step(x = sh.x) )

	with sh.function("test_step_Float3", sh.Float3)(x = sh.Float3):
		sh.return_( sh.g_f3.step(x = sh.x) )

	with sh.function("test_step_Float4", sh.Float4)(x = sh.Float4):
		sh.return_( sh.g_f4.step(x = sh.x) )

	with sh.function("test_step_Float1x1", sh.Float1x1)(x = sh.Float1x1):
		sh.return_( sh.g_f1x1.step(x = sh.x) )

	with sh.function("test_step_Float1x2", sh.Float1x2)(x = sh.Float1x2):
		sh.return_( sh.g_f1x2.step(x = sh.x) )

	with sh.function("test_step_Float1x3", sh.Float1x3)(x = sh.Float1x3):
		sh.return_( sh.g_f1x3.step(x = sh.x) )

	with sh.function("test_step_Float1x4", sh.Float1x4)(x = sh.Float1x4):
		sh.return_( sh.g_f1x4.step(x = sh.x) )

	with sh.function("test_step_Float2x1", sh.Float2x1)(x = sh.Float2x1):
		sh.return_( sh.g_f2x1.step(x = sh.x) )

	with sh.function("test_step_Float2x2", sh.Float2x2)(x = sh.Float2x2):
		sh.return_( sh.g_f2x2.step(x = sh.x) )

	with sh.function("test_step_Float2x3", sh.Float2x3)(x = sh.Float2x3):
		sh.return_( sh.g_f2x3.step(x = sh.x) )

	with sh.function("test_step_Float2x4", sh.Float2x4)(x = sh.Float2x4):
		sh.return_( sh.g_f2x4.step(x = sh.x) )

	with sh.function("test_step_Float3x1", sh.Float3x1)(x = sh.Float3x1):
		sh.return_( sh.g_f3x1.step(x = sh.x) )

	with sh.function("test_step_Float3x2", sh.Float3x2)(x = sh.Float3x2):
		sh.return_( sh.g_f3x2.step(x = sh.x) )

	with sh.function("test_step_Float3x3", sh.Float3x3)(x = sh.Float3x3):
		sh.return_( sh.g_f3x3.step(x = sh.x) )

	with sh.function("test_step_Float3x4", sh.Float3x4)(x = sh.Float3x4):
		sh.return_( sh.g_f3x4.step(x = sh.x) )

	with sh.function("test_step_Float4x1", sh.Float4x1)(x = sh.Float4x1):
		sh.return_( sh.g_f4x1.step(x = sh.x) )

	with sh.function("test_step_Float4x2", sh.Float4x2)(x = sh.Float4x2):
		sh.return_( sh.g_f4x2.step(x = sh.x) )

	with sh.function("test_step_Float4x3", sh.Float4x3)(x = sh.Float4x3):
		sh.return_( sh.g_f4x3.step(x = sh.x) )

	with sh.function("test_step_Float4x4", sh.Float4x4)(x = sh.Float4x4):
		sh.return_( sh.g_f4x4.step(x = sh.x) )

	with sh.function("test_tan_Float", sh.Float)():
		sh.return_( sh.g_f.tan() )

	with sh.function("test_tan_Float1", sh.Float1)():
		sh.return_( sh.g_f1.tan() )

	with sh.function("test_tan_Float2", sh.Float2)():
		sh.return_( sh.g_f2.tan() )

	with sh.function("test_tan_Float3", sh.Float3)():
		sh.return_( sh.g_f3.tan() )

	with sh.function("test_tan_Float4", sh.Float4)():
		sh.return_( sh.g_f4.tan() )

	with sh.function("test_tan_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.tan() )

	with sh.function("test_tan_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.tan() )

	with sh.function("test_tan_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.tan() )

	with sh.function("test_tan_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.tan() )

	with sh.function("test_tan_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.tan() )

	with sh.function("test_tan_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.tan() )

	with sh.function("test_tan_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.tan() )

	with sh.function("test_tan_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.tan() )

	with sh.function("test_tan_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.tan() )

	with sh.function("test_tan_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.tan() )

	with sh.function("test_tan_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.tan() )

	with sh.function("test_tan_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.tan() )

	with sh.function("test_tan_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.tan() )

	with sh.function("test_tan_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.tan() )

	with sh.function("test_tan_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.tan() )

	with sh.function("test_tan_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.tan() )

	with sh.function("test_tanh_Float", sh.Float)():
		sh.return_( sh.g_f.tanh() )

	with sh.function("test_tanh_Float1", sh.Float1)():
		sh.return_( sh.g_f1.tanh() )

	with sh.function("test_tanh_Float2", sh.Float2)():
		sh.return_( sh.g_f2.tanh() )

	with sh.function("test_tanh_Float3", sh.Float3)():
		sh.return_( sh.g_f3.tanh() )

	with sh.function("test_tanh_Float4", sh.Float4)():
		sh.return_( sh.g_f4.tanh() )

	with sh.function("test_tanh_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.tanh() )

	with sh.function("test_tanh_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.tanh() )

	with sh.function("test_tanh_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.tanh() )

	with sh.function("test_tanh_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.tanh() )

	with sh.function("test_tanh_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.tanh() )

	with sh.function("test_tanh_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.tanh() )

	with sh.function("test_tanh_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.tanh() )

	with sh.function("test_tanh_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.tanh() )

	with sh.function("test_tanh_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.tanh() )

	with sh.function("test_tanh_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.tanh() )

	with sh.function("test_tanh_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.tanh() )

	with sh.function("test_tanh_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.tanh() )

	with sh.function("test_tanh_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.tanh() )

	with sh.function("test_tanh_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.tanh() )

	with sh.function("test_tanh_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.tanh() )

	with sh.function("test_tanh_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.tanh() )

	with sh.function("test_trunc_Float", sh.Float)():
		sh.return_( sh.g_f.trunc() )

	with sh.function("test_trunc_Float1", sh.Float1)():
		sh.return_( sh.g_f1.trunc() )

	with sh.function("test_trunc_Float2", sh.Float2)():
		sh.return_( sh.g_f2.trunc() )

	with sh.function("test_trunc_Float3", sh.Float3)():
		sh.return_( sh.g_f3.trunc() )

	with sh.function("test_trunc_Float4", sh.Float4)():
		sh.return_( sh.g_f4.trunc() )

	with sh.function("test_trunc_Float1x1", sh.Float1x1)():
		sh.return_( sh.g_f1x1.trunc() )

	with sh.function("test_trunc_Float1x2", sh.Float1x2)():
		sh.return_( sh.g_f1x2.trunc() )

	with sh.function("test_trunc_Float1x3", sh.Float1x3)():
		sh.return_( sh.g_f1x3.trunc() )

	with sh.function("test_trunc_Float1x4", sh.Float1x4)():
		sh.return_( sh.g_f1x4.trunc() )

	with sh.function("test_trunc_Float2x1", sh.Float2x1)():
		sh.return_( sh.g_f2x1.trunc() )

	with sh.function("test_trunc_Float2x2", sh.Float2x2)():
		sh.return_( sh.g_f2x2.trunc() )

	with sh.function("test_trunc_Float2x3", sh.Float2x3)():
		sh.return_( sh.g_f2x3.trunc() )

	with sh.function("test_trunc_Float2x4", sh.Float2x4)():
		sh.return_( sh.g_f2x4.trunc() )

	with sh.function("test_trunc_Float3x1", sh.Float3x1)():
		sh.return_( sh.g_f3x1.trunc() )

	with sh.function("test_trunc_Float3x2", sh.Float3x2)():
		sh.return_( sh.g_f3x2.trunc() )

	with sh.function("test_trunc_Float3x3", sh.Float3x3)():
		sh.return_( sh.g_f3x3.trunc() )

	with sh.function("test_trunc_Float3x4", sh.Float3x4)():
		sh.return_( sh.g_f3x4.trunc() )

	with sh.function("test_trunc_Float4x1", sh.Float4x1)():
		sh.return_( sh.g_f4x1.trunc() )

	with sh.function("test_trunc_Float4x2", sh.Float4x2)():
		sh.return_( sh.g_f4x2.trunc() )

	with sh.function("test_trunc_Float4x3", sh.Float4x3)():
		sh.return_( sh.g_f4x3.trunc() )

	with sh.function("test_trunc_Float4x4", sh.Float4x4)():
		sh.return_( sh.g_f4x4.trunc() )

